import Link from "next/link";
import { ArrowRight, Banknote, BriefcaseBusiness, Clock3, HandCoins, HeartHandshake, TimerReset } from "lucide-react";
import type { ImpactSummary } from "@/src/domain/impact/metrics";
import { formatImpactCurrency, formatImpactDuration } from "@/src/domain/impact/metrics";

export function ImpactWidgets({ summary, title = "Your impact", admin = false }: { summary: ImpactSummary; title?: string; admin?: boolean }) {
  const metrics = [
    ["Estimated money saved",formatImpactCurrency(summary.estimated_money_saved_cents),Banknote,"Estimated","bg-emerald-50 text-emerald-700"],
    ["Estimated hours saved",`${Math.round(summary.estimated_hours_saved).toLocaleString()} hrs`,Clock3,"Estimated","bg-sky-50 text-sky-700"],
    ["Jobs completed",Math.round(summary.jobs_completed).toLocaleString(),BriefcaseBusiness,"Measured","bg-violet-50 text-violet-700"],
    ["Local spending retained",formatImpactCurrency(summary.local_spending_retained_cents),HeartHandshake,"Estimated","bg-amber-50 text-amber-700"],
  ] as const;
  return <section className="mt-8" aria-labelledby="impact-title"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Optimize Local Impact Engine</p><h2 id="impact-title" className="mt-2 text-2xl font-bold tracking-tight text-slate-950">{title}</h2></div><Link href={admin?"/admin/impact":"/impact"} className="hidden items-center text-sm font-bold text-emerald-700 sm:flex">View reporting <ArrowRight className="ml-1.5 size-4" /></Link></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon,kind,color])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight text-slate-950">{value}</p></div><span className={`grid size-10 place-items-center rounded-xl ${color}`}><Icon className="size-5" /></span></div><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-slate-400">{kind}</p></article>)}</div><div className="mt-4 grid gap-4 md:grid-cols-3"><article className="rounded-2xl bg-slate-950 p-5 text-white"><TimerReset className="size-5 text-emerald-400" /><p className="mt-5 text-xs text-slate-400">Average vendor response</p><p className="mt-1 text-2xl font-bold">{formatImpactDuration(summary.vendor_response_minutes)}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><HandCoins className="size-5 text-emerald-700" /><p className="mt-5 text-xs text-slate-500">Average savings per work order</p><p className="mt-1 text-2xl font-bold">{formatImpactCurrency(summary.average_savings_per_work_order_cents)}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><Clock3 className="size-5 text-rose-600" /><p className="mt-5 text-xs text-slate-500">Emergency response</p><p className="mt-1 text-2xl font-bold">{formatImpactDuration(summary.emergency_response_minutes)}</p></article></div><Link href={admin?"/admin/impact":"/impact"} className="mt-4 inline-flex items-center text-sm font-bold text-emerald-700 sm:hidden">View reporting <ArrowRight className="ml-1.5 size-4" /></Link></section>;
}
