import Link from "next/link";
import { ArrowLeft, Building2, CheckCircle2, Clock3, CreditCard, ExternalLink, FileCheck2, History, MapPin, MessageSquareText, ShieldCheck, Store } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { CopyContactButton } from "@/src/components/admin/copy-contact-button";
import { founderApplicationBadge, founderPaymentBadge, founderStatusLabel } from "@/src/domain/founding-partner/admin";
import { requireUser } from "@/src/lib/auth/session";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";
import { manageFounder } from "../actions";

export const dynamic = "force-dynamic";
const input = "min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100";
const textarea = `${input} min-h-28 py-3`;
type Props = { params: Promise<{ id: string }>; searchParams: Promise<{ result?: string }> };

function money(cents: number, currency = "USD") { return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(cents / 100); }
function dateTime(value: string | null | undefined) { return value ? new Date(value).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" }) : "—"; }
function yesNo(value: boolean | null | undefined) { return value ? "Yes" : "No"; }
function safeUrl(value: string | null | undefined) { return value && /^https?:\/\//i.test(value) ? value : null; }
function Detail({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">{label}</dt><dd className="mt-1.5 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value || "—"}</dd></div>; }
function Section({ title, icon: Icon, children }: { title: string; icon: typeof Building2; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50"><Icon className="size-4.5 text-emerald-700" /></span><h2 className="text-lg font-bold">{title}</h2></div><div className="mt-6">{children}</div></section>; }

export default async function FounderRecordPage({ params, searchParams }: Props) {
  const user = await requireUser();
  if (!user.isSuperAdmin) redirect("/dashboard");
  const { id } = await params;
  if (!/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(id)) notFound();
  const { result } = await searchParams;
  const supabase = await createSupabaseServerClient();
  const { data: founder, error } = await supabase.from("founding_partner_onboardings").select("*").eq("id", id).maybeSingle();
  if (error || !founder) notFound();
  const [{ data: payment }, { data: events }, { data: organization }] = await Promise.all([
    supabase.from("founding_partner_payments").select("*").eq("id", founder.payment_id).maybeSingle(),
    supabase.from("founding_partner_admin_events").select("id,actor_user_id,action,from_status,to_status,notes,occurred_at").eq("onboarding_id", id).order("occurred_at", { ascending: false }),
    founder.vendor_organization_id ? supabase.from("organizations").select("id,name,slug,status").eq("id", founder.vendor_organization_id).maybeSingle() : Promise.resolve({ data: null }),
  ]);
  if (!payment) notFound();
  const actorIds = [...new Set((events ?? []).map(event => event.actor_user_id).filter(Boolean) as string[])];
  const { data: actors } = actorIds.length ? await supabase.from("profiles").select("id,full_name").in("id", actorIds) : { data: [] };
  const actorMap = new Map((actors ?? []).map(actor => [actor.id, actor.full_name]));
  const returnTo = `/admin/founders/${id}`;
  const canReview = ["submitted", "changes_requested"].includes(founder.status);
  const canApprove = ["submitted", "under_review", "changes_requested"].includes(founder.status);
  const canRequestChanges = ["submitted", "under_review", "approved"].includes(founder.status);
  const canReject = ["submitted", "under_review", "approved", "changes_requested"].includes(founder.status);
  const canActivate = ["approved", "suspended"].includes(founder.status);
  const canSuspend = founder.status === "active";

  return <div>
    <Link href="/admin/founders" className="inline-flex items-center text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft className="mr-2 size-4" />All Founding Partners</Link>
    <div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${founderPaymentBadge(payment.payment_status)}`}>Payment: {founderStatusLabel(payment.payment_status)}</span><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${founderApplicationBadge(founder.status)}`}>Application: {founderStatusLabel(founder.status)}</span></div><h1 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">{founder.business_name ?? founder.customer_name ?? "Founding Partner application"}</h1><p className="mt-3 text-sm text-slate-500">{founder.contact_name ?? "Contact not submitted"} · {founder.customer_email}</p></div><div className="flex flex-wrap gap-2"><CopyContactButton label="Email" value={founder.customer_email} /><CopyContactButton label="Phone" value={founder.phone} />{organization ? <Link href={`/marketplace/${organization.slug}`} className="inline-flex min-h-9 items-center rounded-lg bg-slate-950 px-4 text-xs font-bold text-white">Marketplace profile <ExternalLink className="ml-2 size-3.5" /></Link> : null}</div></div>
    {result === "updated" ? <p role="status" className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">Founder record updated and added to the audit history.</p> : result === "error" ? <p role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-800">That action was not allowed from the record’s current state, or a required detail is missing.</p> : null}

    <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(20rem,.6fr)]"><main className="space-y-6">
      <Section title="Payment details" icon={CreditCard}><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="flex items-center gap-2 text-sm font-bold text-emerald-900"><ShieldCheck className="size-4" />Provider-verified payment record</p><p className="mt-1 text-xs text-emerald-800">Admin actions cannot change the amount or mark a payment as verified.</p></div><dl className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Detail label="Status" value={founderStatusLabel(payment.payment_status)} /><Detail label="Amount" value={money(payment.amount_paid_cents, payment.currency)} /><Detail label="Paid" value={dateTime(payment.paid_at)} /><Detail label="Provider" value={payment.payment_provider} /><Detail label="Customer ID" value={<span className="break-all font-mono text-xs">{payment.provider_customer_id}</span>} /><Detail label="Checkout session" value={<span className="break-all font-mono text-xs">{payment.checkout_session_id}</span>} /><Detail label="Payment intent" value={<span className="break-all font-mono text-xs">{payment.payment_intent_id}</span>} /><Detail label="Customer email" value={payment.customer_email} /><Detail label="Customer name" value={payment.customer_name} /></dl></Section>
      <Section title="Business details" icon={Building2}><dl className="grid gap-5 sm:grid-cols-2"><Detail label="Business name" value={founder.business_name} /><Detail label="Contact" value={founder.contact_name} /><Detail label="Email" value={founder.customer_email} /><Detail label="Phone" value={founder.phone} /><Detail label="Website" value={safeUrl(founder.website) ? <a className="font-bold text-emerald-700" href={founder.website} target="_blank" rel="noreferrer">{founder.website}</a> : founder.website} /><Detail label="Years in business" value={founder.years_in_business?.toString()} /><div className="sm:col-span-2"><Detail label="Business description" value={founder.business_description} /></div></dl></Section>
      <Section title="Services and service areas" icon={MapPin}><dl className="grid gap-5 sm:grid-cols-2"><Detail label="Primary category" value={founder.primary_service_category} /><Detail label="Additional categories" value={founder.additional_service_categories?.join(", ")} /><Detail label="Services offered" value={founder.services_offered?.join("\n")} /><Detail label="Service-area cities" value={founder.service_area_cities?.join("\n")} /><Detail label="Service radius" value={founder.service_radius_miles != null ? `${founder.service_radius_miles} miles` : null} /><Detail label="Customer type" value={founder.customer_type ? founderStatusLabel(founder.customer_type) : null} /><Detail label="Emergency service" value={yesNo(founder.emergency_service_available)} /><Detail label="Operating hours" value={founder.operating_hours} /></dl></Section>
      <Section title="Verification details" icon={FileCheck2}><dl className="grid gap-5 sm:grid-cols-2"><Detail label="License applicable" value={yesNo(founder.license_applicable)} /><Detail label="License number" value={founder.license_applicable ? founder.license_number : "Not applicable"} /><Detail label="Insurance status" value={founder.insurance_status ? founderStatusLabel(founder.insurance_status) : null} /><Detail label="Preferred contact" value={founder.preferred_contact_method ? founderStatusLabel(founder.preferred_contact_method) : null} /><Detail label="Google Business Profile" value={safeUrl(founder.google_business_profile_url) ? <a className="font-bold text-emerald-700" href={founder.google_business_profile_url} target="_blank" rel="noreferrer">Open profile</a> : null} /><Detail label="Facebook" value={safeUrl(founder.facebook_page_url) ? <a className="font-bold text-emerald-700" href={founder.facebook_page_url} target="_blank" rel="noreferrer">Open page</a> : null} /><Detail label="Other social links" value={(founder.other_social_links ?? []).map((url: string) => safeUrl(url) ? <a key={url} className="block font-bold text-emerald-700" href={url} target="_blank" rel="noreferrer">{url}</a> : null)} /></dl></Section>
      <Section title="Marketplace profile" icon={Store}><dl className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Detail label="Headline" value={founder.profile_headline} /></div><div className="sm:col-span-2"><Detail label="Company bio" value={founder.company_bio} /></div><Detail label="Logo" value={safeUrl(founder.logo_url) ? <a className="font-bold text-emerald-700" href={founder.logo_url} target="_blank" rel="noreferrer">View logo</a> : null} /><Detail label="Featured image" value={safeUrl(founder.featured_image_url) ? <a className="font-bold text-emerald-700" href={founder.featured_image_url} target="_blank" rel="noreferrer">View image</a> : null} /><Detail label="Free estimates" value={yesNo(founder.offers_free_estimates)} /><Detail label="Financing" value={yesNo(founder.offers_financing)} /><Detail label="Languages" value={founder.languages_spoken?.join(", ")} /><Detail label="Listing record" value={organization ? `${organization.name} · ${founderStatusLabel(organization.status)}` : "Not activated"} /></dl><div className="mt-6 grid gap-2 rounded-xl bg-slate-50 p-4 text-xs text-slate-600 sm:grid-cols-3"><p>Accuracy confirmed: <strong>{yesNo(founder.accuracy_confirmed)}</strong></p><p>Public display consent: <strong>{yesNo(founder.public_display_consent)}</strong></p><p>Terms accepted: <strong>{yesNo(founder.terms_privacy_accepted)}</strong></p></div></Section>
    </main>

    <aside className="space-y-6 xl:sticky xl:top-6 xl:self-start">
      <Section title="Review actions" icon={CheckCircle2}><p className="text-sm leading-6 text-slate-500">Actions change the internal application or listing status. They never modify Stripe payment verification.</p><div className="mt-5 grid gap-3">
        {canReview ? <form action={manageFounder}><input type="hidden" name="onboardingId" value={id} /><input type="hidden" name="action" value="start_review" /><input type="hidden" name="returnTo" value={returnTo} /><button className="min-h-11 w-full rounded-xl border border-blue-200 bg-blue-50 px-4 text-sm font-bold text-blue-800">Start review</button></form> : null}
        {canApprove ? <form action={manageFounder}><input type="hidden" name="onboardingId" value={id} /><input type="hidden" name="action" value="approve" /><input type="hidden" name="returnTo" value={returnTo} /><button className="min-h-11 w-full rounded-xl bg-emerald-700 px-4 text-sm font-black text-white hover:bg-emerald-800">Approve vendor</button></form> : null}
        {canActivate ? <form action={manageFounder}><input type="hidden" name="onboardingId" value={id} /><input type="hidden" name="action" value="activate" /><input type="hidden" name="returnTo" value={returnTo} /><button className="min-h-11 w-full rounded-xl bg-slate-950 px-4 text-sm font-black text-white hover:bg-emerald-700">{founder.status === "suspended" ? "Reactivate marketplace listing" : "Activate marketplace listing"}</button></form> : null}
        {canSuspend ? <form action={manageFounder}><input type="hidden" name="onboardingId" value={id} /><input type="hidden" name="action" value="suspend" /><input type="hidden" name="returnTo" value={returnTo} /><button className="min-h-11 w-full rounded-xl border border-rose-200 bg-rose-50 px-4 text-sm font-bold text-rose-800">Suspend marketplace listing</button></form> : null}
      </div>{canRequestChanges || canReject ? <div className="mt-5 space-y-4 border-t border-slate-100 pt-5">{canRequestChanges ? <form action={manageFounder}><input type="hidden" name="onboardingId" value={id} /><input type="hidden" name="action" value="request_changes" /><input type="hidden" name="returnTo" value={returnTo} /><label className="text-xs font-bold text-slate-600">Vendor-visible change request<textarea className={textarea} name="notes" required minLength={5} maxLength={4000} placeholder="Explain exactly what needs to be updated." /></label><button className="mt-2 min-h-10 w-full rounded-xl bg-amber-100 px-4 text-xs font-black text-amber-900">Request changes</button></form> : null}{canReject ? <form action={manageFounder}><input type="hidden" name="onboardingId" value={id} /><input type="hidden" name="action" value="reject" /><input type="hidden" name="returnTo" value={returnTo} /><label className="text-xs font-bold text-slate-600">Rejection reason<textarea className={textarea} name="notes" required minLength={5} maxLength={4000} placeholder="Record the reason for rejection." /></label><button className="mt-2 min-h-10 w-full rounded-xl bg-rose-100 px-4 text-xs font-black text-rose-900">Reject vendor</button></form> : null}</div> : null}</Section>
      <Section title="Internal notes" icon={MessageSquareText}><form action={manageFounder}><input type="hidden" name="onboardingId" value={id} /><input type="hidden" name="action" value="save_notes" /><input type="hidden" name="returnTo" value={returnTo} /><label className="sr-only" htmlFor="internal-notes">Internal notes</label><textarea id="internal-notes" className={textarea} name="notes" maxLength={4000} defaultValue={founder.internal_notes ?? ""} placeholder="Private review context. This is not shown to the vendor." /><button className="mt-3 min-h-10 w-full rounded-xl border border-slate-200 px-4 text-xs font-bold hover:bg-slate-50">Save internal notes</button></form></Section>
      <Section title="Status history" icon={History}><ol className="space-y-4"><li className="relative border-l-2 border-emerald-200 pl-4"><p className="text-sm font-bold">Payment confirmed</p><p className="mt-1 text-xs text-slate-400">{dateTime(payment.paid_at)}</p></li>{founder.submitted_at ? <li className="relative border-l-2 border-blue-200 pl-4"><p className="text-sm font-bold">Application submitted</p><p className="mt-1 text-xs text-slate-400">{dateTime(founder.submitted_at)}</p></li> : null}{(events ?? []).map(event => <li key={event.id} className="relative border-l-2 border-slate-200 pl-4"><p className="text-sm font-bold">{founderStatusLabel(event.action)}</p><p className="mt-1 text-xs text-slate-500">{event.from_status ? `${founderStatusLabel(event.from_status)} → ${founderStatusLabel(event.to_status ?? event.from_status)}` : founderStatusLabel(event.to_status ?? founder.status)}</p>{event.notes ? <p className="mt-2 rounded-lg bg-slate-50 p-2 text-xs leading-5 text-slate-600">{event.notes}</p> : null}<p className="mt-2 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 className="size-3" />{dateTime(event.occurred_at)} · {actorMap.get(event.actor_user_id) ?? event.actor_user_id?.slice(0, 8) ?? "System"}</p></li>)}</ol></Section>
    </aside></div>
  </div>;
}
