import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Award, Banknote, Clock3, Download, RotateCcw, ShieldAlert, Users } from "lucide-react";
import { approveFoundingPayment, editFoundingDisplay, editReservedBusiness, reassignFoundingSeat, resendFoundingConfirmation, updateFoundingSeat } from "./actions";
import { formatFoundingNumber } from "@/src/lib/founding-fifty/board";
import { requireUser } from "@/src/lib/auth/session";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";

export const dynamic = "force-dynamic";
const input = "min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600";

export default async function FoundingFiftyAdminPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const user = await requireUser();
  if (!user.isSuperAdmin) redirect("/dashboard");
  const { status } = await searchParams;
  const supabase = await createSupabaseServerClient();
  await supabase.rpc("release_expired_founding_holds", { target_program_id: null });
  let seatQuery = supabase.from("founding_seats").select("id,seat_number,status,reserved_business_name,display_business_name,display_city,logo_url,vendor_id,founding_verticals(name)").order("seat_number");
  if (status && ["available","pending_payment","claimed","reserved","disabled"].includes(status)) seatQuery = seatQuery.eq("status",status);
  const [{ data: seats }, { data: claims }, { data: program }] = await Promise.all([
    seatQuery,
    supabase.from("founding_claims").select("id,seat_id,business_name,contact_name,email,status,payment_amount_cents,payment_reference,expires_at,created_at").order("created_at",{ascending:false}),
    supabase.from("founding_programs").select("total_seats,price_cents").eq("slug","founding-fifty").single(),
  ]);
  const claimed = seats?.filter(s=>s.status==="claimed").length ?? 0;
  const revenue = (claims ?? []).filter(c=>c.status==="confirmed").reduce((sum,c)=>sum+c.payment_amount_cents,0);
  const metrics = [["Claimed seats",claimed,Users],["Seats remaining",(program?.total_seats??50)-claimed,Award],["Confirmed revenue",`$${(revenue/100).toLocaleString("en-US")}`,Banknote],["Potential remaining",`$${((((program?.total_seats??50)-claimed)*(program?.price_cents??29900))/100).toLocaleString("en-US")}`,Clock3]] as const;
  return <div><Link href="/admin" className="inline-flex items-center text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft className="mr-2 size-4" />Admin overview</Link><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Program administration</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">The Founding Fifty</h1><p className="mt-2 text-sm text-slate-500">Manage holds, payments, permanent numbers, display records, and confirmation delivery.</p></div><a href="/admin/founding-fifty/export" className="inline-flex min-h-11 items-center justify-center rounded-full border border-slate-200 bg-white px-5 text-sm font-bold text-slate-700 hover:bg-slate-50"><Download className="mr-2 size-4" />Export CSV</a></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold">{typeof value==="number"?value.toLocaleString():value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-emerald-50"><Icon className="size-5 text-emerald-700" /></span></div></article>)}</section>
    <nav className="mt-8 flex flex-wrap gap-2">{["all","available","pending_payment","claimed","reserved","disabled"].map(item=><Link key={item} href={item==="all"?"/admin/founding-fifty":`/admin/founding-fifty?status=${item}`} className={`rounded-full px-4 py-2 text-xs font-bold ${(!status&&item==="all")||status===item?"bg-slate-950 text-white":"border border-slate-200 bg-white text-slate-600"}`}>{item.replaceAll("_"," ")}</Link>)}</nav>
    <section className="mt-6 grid gap-4 xl:grid-cols-2">{(seats??[]).map(seat=>{const vertical=seat.founding_verticals as unknown as {name:string}|null;const seatClaims=(claims??[]).filter(c=>c.seat_id===seat.id);const activeClaim=seatClaims.find(c=>["pending_payment","payment_submitted","awaiting_verification"].includes(c.status));return <article key={seat.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black text-emerald-700">{formatFoundingNumber(seat.seat_number)} · {vertical?.name}</p><h2 className="mt-2 text-lg font-bold">{seat.display_business_name??seat.reserved_business_name??"Open seat"}</h2><p className="mt-1 text-xs capitalize text-slate-500">{seat.status.replaceAll("_"," ")}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${seat.status==="claimed"?"bg-amber-100 text-amber-800":seat.status==="available"?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"}`}>{seat.status.replaceAll("_"," ")}</span></div>
      {seat.status==="available"?<form action={updateFoundingSeat} className="mt-5 flex gap-2"><input type="hidden" name="seatId" value={seat.id}/><input type="hidden" name="action" value="reserve"/><input className={input} name="businessName" required placeholder="Editable reserved business name"/><button className="rounded-lg bg-slate-950 px-4 text-xs font-bold text-white">Reserve</button></form>:null}
      {seat.status==="reserved"?<div className="mt-5 space-y-2"><form action={editReservedBusiness} className="flex gap-2"><input type="hidden" name="seatId" value={seat.id}/><input className={input} name="businessName" required defaultValue={seat.reserved_business_name??""}/><button className="rounded-lg bg-slate-950 px-4 text-xs font-bold text-white">Save name</button></form><form action={updateFoundingSeat}><input type="hidden" name="seatId" value={seat.id}/><input type="hidden" name="action" value="release"/><button className="inline-flex min-h-10 items-center rounded-lg border border-slate-200 px-4 text-xs font-bold"><RotateCcw className="mr-2 size-3.5"/>Release reservation</button></form></div>:null}
      {activeClaim?<div className="mt-5 rounded-xl bg-amber-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-amber-800">Awaiting verification</p><p className="mt-2 text-sm font-bold">{activeClaim.business_name}</p><p className="mt-1 text-xs text-amber-800/70">{activeClaim.contact_name} · {activeClaim.email}</p><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto]"><form action={approveFoundingPayment} className="contents"><input type="hidden" name="claimId" value={activeClaim.id}/><input className={input} name="paymentReference" required placeholder="Verified PayPal reference"/><button className="rounded-lg bg-emerald-700 px-4 text-xs font-black text-white">Approve payment</button></form></div><form action={updateFoundingSeat} className="mt-2"><input type="hidden" name="seatId" value={seat.id}/><input type="hidden" name="claimId" value={activeClaim.id}/><input type="hidden" name="action" value="reject_claim"/><button className="text-xs font-bold text-rose-700">Reject and release</button></form></div>:null}
      {seat.status==="claimed"?<div className="mt-5 space-y-4"><form action={editFoundingDisplay} encType="multipart/form-data" className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="seatId" value={seat.id}/><input className={input} name="businessName" required defaultValue={seat.display_business_name??""} placeholder="Display business name"/><input className={input} name="city" defaultValue={seat.display_city??""} placeholder="City"/><input className={`${input} sm:col-span-2`} name="logoUrl" type="url" defaultValue={seat.logo_url??""} placeholder="Existing public logo URL"/><input className="text-xs sm:col-span-2" name="logo" type="file" accept="image/jpeg,image/png,image/webp"/><button className="min-h-10 rounded-lg bg-slate-950 px-4 text-xs font-bold text-white sm:col-span-2">Save public display</button></form>{seatClaims.find(c=>c.status==="confirmed")?<form action={resendFoundingConfirmation}><input type="hidden" name="claimId" value={seatClaims.find(c=>c.status==="confirmed")!.id}/><button className="text-xs font-bold text-emerald-700">Send confirmation email again</button></form>:null}<details className="rounded-xl bg-rose-50 p-3"><summary className="flex cursor-pointer gap-2 text-xs font-bold leading-5 text-rose-800"><ShieldAlert className="mt-0.5 size-4 shrink-0"/>Danger: reassign this permanent founding number</summary><form action={reassignFoundingSeat} className="mt-3 grid gap-2"><input type="hidden" name="seatId" value={seat.id}/><input className={input} name="vendorId" required placeholder="Target vendor organization UUID"/><input className={input} name="confirmationPhrase" required placeholder="Type REASSIGN PERMANENT FOUNDING NUMBER"/><button className="min-h-10 rounded-lg bg-rose-700 px-4 text-xs font-black text-white">Reassign with permanent audit record</button></form></details></div>:null}
      {seatClaims.some(c=>["expired","payment_failed","payment_cancelled","rejected"].includes(c.status))?<details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-xs font-bold text-slate-500">Abandoned or unsuccessful claims ({seatClaims.filter(c=>["expired","payment_failed","payment_cancelled","rejected"].includes(c.status)).length})</summary><ul className="mt-3 space-y-2">{seatClaims.filter(c=>["expired","payment_failed","payment_cancelled","rejected"].includes(c.status)).map(c=><li key={c.id} className="text-xs text-slate-500">{c.business_name} · {c.status.replaceAll("_"," ")}</li>)}</ul></details>:null}
    </article>})}</section>
  </div>;
}
