import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Award, Banknote, Clock3, CreditCard, Download, RotateCcw, ShieldAlert, Users } from "lucide-react";
import { approveFoundingPayment, editFoundingDisplay, editReservedBusiness, reassignFoundingSeat, resendFoundingConfirmation, updateFoundingPartnerApplication, updateFoundingSeat } from "./actions";
import { formatFoundingNumber } from "@/src/lib/founding-fifty/board";
import { requireUser } from "@/src/lib/auth/session";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";

export const dynamic = "force-dynamic";
const input = "min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-600";

export default async function FoundingFiftyAdminPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const user = await requireUser();
  if (!user.isSuperAdmin) redirect("/dashboard");
  const { status } = await searchParams;
  const supabase = await createSupabaseServerClient();
  await supabase.rpc("release_expired_founding_holds", { target_program_id: null });
  let seatQuery = supabase.from("founding_seats").select("id,seat_number,status,reserved_business_name,display_business_name,display_city,logo_url,vendor_id,founding_verticals(name)").order("seat_number");
  if (status && ["available","pending_payment","claimed","reserved","disabled"].includes(status)) seatQuery = seatQuery.eq("status",status);
  const [{ data: seats }, { data: claims }, { data: program }, { data: directPayments }, { data: directOnboardings }] = await Promise.all([
    seatQuery,
    supabase.from("founding_claims").select("id,seat_id,business_name,contact_name,email,status,payment_amount_cents,payment_reference,expires_at,created_at").order("created_at",{ascending:false}),
    supabase.from("founding_programs").select("total_seats,price_cents").eq("slug","founding-fifty").single(),
    supabase.from("founding_partner_payments").select("id,provider_customer_id,checkout_session_id,payment_intent_id,amount_paid_cents,currency,payment_status,customer_email,customer_name,membership_type,paid_at").order("paid_at",{ascending:false}),
    supabase.from("founding_partner_onboardings").select("*").order("created_at",{ascending:false}),
  ]);
  const claimed = seats?.filter(s=>s.status==="claimed").length ?? 0;
  const directPaid = (directPayments ?? []).filter(payment=>payment.payment_status==="paid");
  const revenue = (claims ?? []).filter(c=>c.status==="confirmed").reduce((sum,c)=>sum+c.payment_amount_cents,0)+directPaid.reduce((sum,payment)=>sum+payment.amount_paid_cents,0);
  const enrollmentCount = claimed+directPaid.length;
  const metrics = [["Claimed seats",claimed,Users],["Paid applicants",directPaid.length,CreditCard],["Capacity remaining",Math.max(0,(program?.total_seats??50)-enrollmentCount),Award],["Confirmed revenue",`$${(revenue/100).toLocaleString("en-US")}`,Banknote],["Pending profiles",(directOnboardings??[]).filter(item=>item.status==="paid_onboarding_incomplete").length,Clock3]] as const;
  return <div><Link href="/admin" className="inline-flex items-center text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft className="mr-2 size-4" />Admin overview</Link><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Program administration</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">The Founding Fifty</h1><p className="mt-2 text-sm text-slate-500">Manage holds, payments, permanent numbers, display records, and confirmation delivery.</p></div><a href="/admin/founding-fifty/export" className="inline-flex min-h-11 items-center justify-center rounded-full border border-slate-200 bg-white px-5 text-sm font-bold text-slate-700 hover:bg-slate-50"><Download className="mr-2 size-4" />Export CSV</a></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label,value,Icon])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold">{typeof value==="number"?value.toLocaleString():value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-emerald-50"><Icon className="size-5 text-emerald-700" /></span></div></article>)}</section>
    <section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-emerald-700">Direct Stripe checkout</p><h2 className="mt-1 text-2xl font-bold">Paid Founding Partner applicants</h2><p className="mt-2 text-sm text-slate-500">Every row below is backed by a verified $299 Stripe payment and one idempotent onboarding record.</p></div><CreditCard className="size-7 text-emerald-700" /></div>{directPaid.length?<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Payment</th><th className="px-3 py-3">Profile</th><th className="px-3 py-3">Service area</th><th className="px-3 py-3">Paid</th></tr></thead><tbody className="divide-y divide-slate-100">{directPaid.map(payment=>{const onboarding=(directOnboardings??[]).find(item=>item.payment_id===payment.id);return <tr key={payment.id} className="align-top"><td className="px-3 py-4"><p className="font-bold text-slate-900">{onboarding?.business_name??payment.customer_name??"Profile pending"}</p><p className="mt-1 text-xs text-slate-500">{payment.customer_email}</p>{onboarding?.contact_name?<p className="mt-1 text-xs text-slate-500">{onboarding.contact_name} · {onboarding.phone}</p>:null}</td><td className="px-3 py-4"><p className="font-bold text-emerald-700">${(payment.amount_paid_cents/100).toFixed(2)} {payment.currency}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{payment.payment_intent_id}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{payment.checkout_session_id}</p></td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${onboarding?.status==="profile_submitted"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{(onboarding?.status??"pending").replaceAll("_"," ")}</span></td><td className="px-3 py-4"><p className="text-slate-700">{onboarding?.service_category??"Not submitted"}</p><p className="mt-1 text-xs text-slate-500">{onboarding?.city??"—"}</p></td><td className="px-3 py-4 text-xs text-slate-500">{new Date(payment.paid_at).toLocaleString("en-US")}</td></tr>})}</tbody></table></div>:<p className="mt-6 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No direct Founding Partner payments have been recorded yet.</p>}</section>
    <section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
      <div>
        <p className="text-sm font-semibold text-emerald-700">Application review</p>
        <h2 className="mt-1 text-2xl font-bold">Founding Partner profiles</h2>
        <p className="mt-2 text-sm text-slate-500">Review every saved field, request changes, and control the application lifecycle.</p>
      </div>
      <div className="mt-6 grid gap-4">
        {(directOnboardings ?? []).map(application => {
          const payment = directPaid.find(item => item.id === application.payment_id);
          return <article key={application.id} className="rounded-2xl border border-slate-200 p-5">
            <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
              <div>
                <p className="text-lg font-bold">{application.business_name ?? payment?.customer_name ?? "Onboarding incomplete"}</p>
                <p className="mt-1 text-sm text-slate-500">{payment?.customer_email}{application.contact_name ? ` · ${application.contact_name}` : ""}{application.phone ? ` · ${application.phone}` : ""}</p>
                <span className="mt-3 inline-flex rounded-full bg-amber-100 px-3 py-1 text-[10px] font-black uppercase text-amber-800">{application.status.replaceAll("_", " ")}</span>
              </div>
              {application.submitted_at ? <p className="text-xs text-slate-400">Submitted {new Date(application.submitted_at).toLocaleString("en-US")}</p> : null}
            </div>
            <details className="mt-5 rounded-xl bg-slate-50 p-4">
              <summary className="cursor-pointer text-sm font-bold text-slate-700">View complete application</summary>
              <div className="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3">
                <div><p className="font-bold">Business</p><p className="mt-1 text-slate-500">{application.business_description || "No description yet"}</p><p className="mt-2 text-slate-500">{application.years_in_business ?? "—"} years · {application.website || "No website"}</p></div>
                <div><p className="font-bold">Services</p><p className="mt-1 text-slate-500">{application.primary_service_category || "Not selected"}</p><p className="mt-2 text-slate-500">{application.services_offered?.join(", ") || "No services listed"}</p></div>
                <div><p className="font-bold">Coverage</p><p className="mt-1 text-slate-500">{application.service_area_cities?.join(", ") || "No cities listed"}</p><p className="mt-2 text-slate-500">{application.service_radius_miles ?? "—"} mile radius · {application.customer_type || "—"}</p></div>
                <div><p className="font-bold">Verification</p><p className="mt-1 text-slate-500">License: {application.license_applicable ? application.license_number || "Missing" : "Not applicable"}</p><p className="mt-2 text-slate-500">Insurance: {application.insurance_status || "—"}</p></div>
                <div><p className="font-bold">Marketplace copy</p><p className="mt-1 text-slate-500">{application.profile_headline || "No headline"}</p><p className="mt-2 text-slate-500">{application.company_bio || "No bio"}</p></div>
                <div><p className="font-bold">Profile options</p><p className="mt-1 text-slate-500">Languages: {application.languages_spoken?.join(", ") || "—"}</p><p className="mt-2 text-slate-500">Free estimates: {application.offers_free_estimates ? "Yes" : "No"} · Financing: {application.offers_financing ? "Yes" : "No"}</p></div>
              </div>
              <div className="mt-4 flex flex-wrap gap-3 text-xs font-bold text-emerald-700">{application.logo_url ? <a href={application.logo_url} target="_blank" rel="noreferrer">View logo</a> : null}{application.featured_image_url ? <a href={application.featured_image_url} target="_blank" rel="noreferrer">View featured image</a> : null}{application.google_business_profile_url ? <a href={application.google_business_profile_url} target="_blank" rel="noreferrer">Google profile</a> : null}{application.facebook_page_url ? <a href={application.facebook_page_url} target="_blank" rel="noreferrer">Facebook</a> : null}</div>
            </details>
            {application.status !== "paid_onboarding_incomplete" ? <form action={updateFoundingPartnerApplication} className="mt-5 grid gap-3 rounded-xl border border-slate-200 p-4 lg:grid-cols-[220px_1fr_auto]">
              <input type="hidden" name="onboardingId" value={application.id} />
              <select className={input} name="status" defaultValue={application.status === "submitted" ? "under_review" : application.status}>
                <option value="under_review">Under review</option><option value="approved">Approved</option><option value="changes_requested">Changes requested</option><option value="rejected">Rejected</option><option value="active">Active</option><option value="suspended">Suspended</option>
              </select>
              <input className={input} name="reviewNotes" defaultValue={application.review_notes ?? ""} placeholder="Review note (required when requesting changes)" />
              <button className="min-h-10 rounded-lg bg-slate-950 px-5 text-xs font-bold text-white">Save review</button>
            </form> : null}
          </article>;
        })}
      </div>
    </section>
    <nav className="mt-8 flex flex-wrap gap-2">{["all","available","pending_payment","claimed","reserved","disabled"].map(item=><Link key={item} href={item==="all"?"/admin/founding-fifty":`/admin/founding-fifty?status=${item}`} className={`rounded-full px-4 py-2 text-xs font-bold ${(!status&&item==="all")||status===item?"bg-slate-950 text-white":"border border-slate-200 bg-white text-slate-600"}`}>{item.replaceAll("_"," ")}</Link>)}</nav>
    <section className="mt-6 grid gap-4 xl:grid-cols-2">{(seats??[]).map(seat=>{const vertical=seat.founding_verticals as unknown as {name:string}|null;const seatClaims=(claims??[]).filter(c=>c.seat_id===seat.id);const activeClaim=seatClaims.find(c=>["pending_payment","payment_submitted","awaiting_verification"].includes(c.status));return <article key={seat.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black text-emerald-700">{formatFoundingNumber(seat.seat_number)} · {vertical?.name}</p><h2 className="mt-2 text-lg font-bold">{seat.display_business_name??seat.reserved_business_name??"Open seat"}</h2><p className="mt-1 text-xs capitalize text-slate-500">{seat.status.replaceAll("_"," ")}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${seat.status==="claimed"?"bg-amber-100 text-amber-800":seat.status==="available"?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"}`}>{seat.status.replaceAll("_"," ")}</span></div>
      {seat.status==="available"?<form action={updateFoundingSeat} className="mt-5 flex gap-2"><input type="hidden" name="seatId" value={seat.id}/><input type="hidden" name="action" value="reserve"/><input className={input} name="businessName" required placeholder="Editable reserved business name"/><button className="rounded-lg bg-slate-950 px-4 text-xs font-bold text-white">Reserve</button></form>:null}
      {seat.status==="reserved"?<div className="mt-5 space-y-2"><form action={editReservedBusiness} className="flex gap-2"><input type="hidden" name="seatId" value={seat.id}/><input className={input} name="businessName" required defaultValue={seat.reserved_business_name??""}/><button className="rounded-lg bg-slate-950 px-4 text-xs font-bold text-white">Save name</button></form><form action={updateFoundingSeat}><input type="hidden" name="seatId" value={seat.id}/><input type="hidden" name="action" value="release"/><button className="inline-flex min-h-10 items-center rounded-lg border border-slate-200 px-4 text-xs font-bold"><RotateCcw className="mr-2 size-3.5"/>Release reservation</button></form></div>:null}
      {activeClaim?<div className="mt-5 rounded-xl bg-amber-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-amber-800">Awaiting verification</p><p className="mt-2 text-sm font-bold">{activeClaim.business_name}</p><p className="mt-1 text-xs text-amber-800/70">{activeClaim.contact_name} · {activeClaim.email}</p><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto]"><form action={approveFoundingPayment} className="contents"><input type="hidden" name="claimId" value={activeClaim.id}/><input className={input} name="paymentReference" required placeholder="Stripe Checkout Session ID (cs_...)"/><button className="rounded-lg bg-emerald-700 px-4 text-xs font-black text-white">Verify with Stripe</button></form></div><form action={updateFoundingSeat} className="mt-2"><input type="hidden" name="seatId" value={seat.id}/><input type="hidden" name="claimId" value={activeClaim.id}/><input type="hidden" name="action" value="reject_claim"/><button className="text-xs font-bold text-rose-700">Reject and release</button></form></div>:null}
      {seat.status==="claimed"?<div className="mt-5 space-y-4"><form action={editFoundingDisplay} encType="multipart/form-data" className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="seatId" value={seat.id}/><input className={input} name="businessName" required defaultValue={seat.display_business_name??""} placeholder="Display business name"/><input className={input} name="city" defaultValue={seat.display_city??""} placeholder="City"/><input className={`${input} sm:col-span-2`} name="logoUrl" type="url" defaultValue={seat.logo_url??""} placeholder="Existing public logo URL"/><input className="text-xs sm:col-span-2" name="logo" type="file" accept="image/jpeg,image/png,image/webp"/><button className="min-h-10 rounded-lg bg-slate-950 px-4 text-xs font-bold text-white sm:col-span-2">Save public display</button></form>{seatClaims.find(c=>c.status==="confirmed")?<form action={resendFoundingConfirmation}><input type="hidden" name="claimId" value={seatClaims.find(c=>c.status==="confirmed")!.id}/><button className="text-xs font-bold text-emerald-700">Send confirmation email again</button></form>:null}<details className="rounded-xl bg-rose-50 p-3"><summary className="flex cursor-pointer gap-2 text-xs font-bold leading-5 text-rose-800"><ShieldAlert className="mt-0.5 size-4 shrink-0"/>Danger: reassign this permanent founding number</summary><form action={reassignFoundingSeat} className="mt-3 grid gap-2"><input type="hidden" name="seatId" value={seat.id}/><input className={input} name="vendorId" required placeholder="Target vendor organization UUID"/><input className={input} name="confirmationPhrase" required placeholder="Type REASSIGN PERMANENT FOUNDING NUMBER"/><button className="min-h-10 rounded-lg bg-rose-700 px-4 text-xs font-black text-white">Reassign with permanent audit record</button></form></details></div>:null}
      {seatClaims.some(c=>["expired","payment_failed","payment_cancelled","rejected"].includes(c.status))?<details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-xs font-bold text-slate-500">Abandoned or unsuccessful claims ({seatClaims.filter(c=>["expired","payment_failed","payment_cancelled","rejected"].includes(c.status)).length})</summary><ul className="mt-3 space-y-2">{seatClaims.filter(c=>["expired","payment_failed","payment_cancelled","rejected"].includes(c.status)).map(c=><li key={c.id} className="text-xs text-slate-500">{c.business_name} · {c.status.replaceAll("_"," ")}</li>)}</ul></details>:null}
    </article>})}</section>
  </div>;
}
