import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { filterFounderEnrollments, founderSummary, isActiveFounder, isPaidFounder, type FounderEnrollment } from "../src/domain/founding-vendors/dashboard";

const page = readFileSync(new URL("../app/(platform)/admin/founding-vendors/page.tsx", import.meta.url), "utf8");
const row = (overrides: Partial<FounderEnrollment> = {}): FounderEnrollment => ({ id: "1", businessName: "Perfect Temp", contactName: "Pat", email: "pat@example.com", phone: "815-555-0100", industry: "HVAC", source: "Guest Founder checkout", paymentStatus: "paid", membershipStatus: "active", amountPaidCents: 29900, accountClaimed: false, createdAt: "2026-07-20T00:00:00Z", updatedAt: "2026-07-20T00:00:00Z", activatedAt: "2026-07-20T00:00:00Z", stripeCustomerId: "cus_test", checkoutSessionId: "cs_test", paymentIntentId: "pi_test", ...overrides });

test("Founding Vendor dashboard requires Super Admin access and is read-only", () => { assert.match(page, /requireUser\(\)/); assert.match(page, /!user\.isSuperAdmin/); assert.doesNotMatch(page, /"use server"/); assert.doesNotMatch(page, /\.update\(/); });
test("summary calculations distinguish active, pending, paid, unclaimed, and capacity", () => { const result = founderSummary([row(), row({ id: "2", paymentStatus: "pending", membershipStatus: "pending", amountPaidCents: 0, accountClaimed: true })], 50, 3); assert.equal(result.active, 1); assert.equal(result.pending, 1); assert.equal(result.paid, 1); assert.equal(result.unclaimed, 1); assert.equal(result.remaining, 47); assert.equal(result.revenueCents, 29900); });
test("paid and active classification require supported data", () => { assert.equal(isPaidFounder(row()), true); assert.equal(isPaidFounder(row({ paymentStatus: "failed" })), false); assert.equal(isPaidFounder(row({ amountPaidCents: 0 })), false); assert.equal(isActiveFounder(row()), true); assert.equal(isActiveFounder(row({ membershipStatus: "pending" })), false); });
test("search, filters, and unclaimed filter work across required fields", () => { const rows = [row(), row({ id: "2", businessName: "Northside Plumbing", email: "north@example.com", phone: "779-555-0100", industry: "Plumbing", accountClaimed: true, salesStage: undefined } as Partial<FounderEnrollment>)]; assert.equal(filterFounderEnrollments(rows, { q: "815-555" }).length, 1); assert.equal(filterFounderEnrollments(rows, { industry: "Plumbing" }).length, 1); assert.equal(filterFounderEnrollments(rows, { status: "unclaimed" }).length, 1); });
test("dashboard uses existing Founder ledgers and keeps public reservations separate", () => { for (const source of ["founding_partner_payments", "founding_partner_onboardings", "vendor_membership_guest_claims", "vendor_enrollments", "vendor_memberships"]) assert.match(page, new RegExp(source)); assert.match(page, /FOUNDING_VENDOR_RESERVATION_SUMMARY/); assert.match(page, /not combined with paid or active memberships/); });
