import type { AppUser } from "@/src/domain/auth/types";
import { managePropertyManagerServiceRequest } from "@/app/(platform)/admin/service-requests/actions";
import { listEligibleFirebaseVendors, listFirebaseServiceRequestsForAdmin } from "@/src/lib/firebase/service-requests";

const input="min-h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm";
const statusCopy: Record<string, string> = { submitted: "New", reviewing: "Reviewing", assigned: "Vendor invited", accepted: "Accepted", in_progress: "In progress", completed: "Completed", canceled: "Canceled" };
export async function FirebaseAdminServiceRequests({user}:{user:AppUser}){
  const requests=await listFirebaseServiceRequestsForAdmin(user);
  const eligibleByRequest=new Map(await Promise.all(requests.filter(request=>["submitted","reviewing","assigned"].includes(request.status)).map(async request=>[request.id,await listEligibleFirebaseVendors({requestId:request.id,user})] as const)));
  return <div><p className="text-sm font-semibold text-emerald-700">Connect Match</p><h1 className="mt-1 text-4xl font-semibold">Service Requests</h1><p className="mt-3 text-sm text-slate-500">Manual, rule-based matching using category, service-area, active-membership, and published-profile criteria. Membership priority orders otherwise eligible candidates; it does not override eligibility.</p><div className="mt-6 grid gap-3">{requests.map(request=>{const candidates=eligibleByRequest.get(request.id)??[];const actionable=["submitted","reviewing","assigned"].includes(request.status);return <details key={request.id} className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">{request.propertyName} · {request.categoryName} · {statusCopy[request.status]??request.status}</summary><p className="mt-3 text-sm">{request.problemDescription}</p><p className="mt-2 text-xs text-slate-500">Matching criteria: {request.categoryName} in {request.serviceAreaKey}. {candidates.length} eligible vendor{candidates.length===1?"":"s"}.</p>{actionable?<><form action={managePropertyManagerServiceRequest} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="requestId" value={request.id}/><select className={input} name="vendorId" required defaultValue=""><option value="" disabled>{candidates.length?"Choose an eligible vendor":"No eligible vendors"}</option>{candidates.map(vendor=><option key={vendor.id} value={vendor.id}>{String(vendor.businessName)} · priority {String(vendor.membershipPriority)}</option>)}</select><input type="hidden" name="status" value="assigned"/><input className={input} name="note" placeholder="Internal assignment note (optional)"/><button disabled={!candidates.length} className="rounded-xl bg-slate-950 px-4 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Assign vendor</button></form><div className="mt-3 flex gap-4">{request.status==="submitted"?<form action={managePropertyManagerServiceRequest}><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="status" value="reviewing"/><button className="text-xs font-bold text-emerald-800">Mark under review</button></form>:null}<form action={managePropertyManagerServiceRequest}><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="status" value="cancelled"/><button className="text-xs font-bold text-rose-700">Cancel request</button></form></div></>:<p className="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">This request is no longer assignable. Its event history remains in the private request record.</p>}</details>})}</div>{!requests.length?<section className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No requests are waiting for review.</section>:null}</div>;
}
