import type { AppUser } from "@/src/domain/auth/types";
import { managePropertyManagerServiceRequest } from "@/app/(platform)/admin/service-requests/actions";
import { listEligibleFirebaseVendors, listFirebaseServiceRequestsForAdmin } from "@/src/lib/firebase/service-requests";

const input="min-h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm";
export async function FirebaseAdminServiceRequests({user}:{user:AppUser}){
  const requests=await listFirebaseServiceRequestsForAdmin(user);
  const eligibleByRequest=new Map(await Promise.all(requests.filter(request=>["submitted","reviewing","assigned"].includes(request.status)).map(async request=>[request.id,await listEligibleFirebaseVendors({requestId:request.id,user})] as const)));
  return <div><p className="text-sm font-semibold text-emerald-700">Connect Match</p><h1 className="mt-1 text-4xl font-semibold">Service Requests</h1><p className="mt-3 text-sm text-slate-500">Manual, rule-based matching. Tier is context only after eligibility.</p><div className="mt-6 grid gap-3">{requests.map(request=><details key={request.id} className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">{request.propertyName} · {request.categoryName} · {request.status}</summary><p className="mt-3 text-sm">{request.problemDescription}</p><p className="mt-2 text-xs text-slate-500">Service area: {request.serviceAreaKey}</p><form action={managePropertyManagerServiceRequest} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="requestId" value={request.id}/><select className={input} name="vendorId" defaultValue=""><option value="">Eligible vendor</option>{(eligibleByRequest.get(request.id)??[]).map(vendor=><option key={vendor.id} value={vendor.id}>{String(vendor.businessName)} · priority {String(vendor.membershipPriority)}</option>)}</select><select className={input} name="status" defaultValue={request.status==="submitted"?"reviewing":"assigned"}><option value="reviewing">Reviewing</option><option value="assigned">Assign</option><option value="cancelled">Cancel</option></select><input className={input} name="note" placeholder="Timeline note"/><button className="rounded-xl bg-slate-950 px-4 text-xs font-bold text-white">Save</button></form></details>)}</div></div>;
}
