import Link from "next/link";
import { ArrowLeft, ClipboardCheck } from "lucide-react";
import type { AppUser, Membership } from "@/src/domain/auth/types";
import type { VendorProfileDocument } from "@/src/domain/firebase-platform/types";
import { saveVendorProfile } from "@/app/(platform)/vendor/profile/actions";
import { getPlatformFirestore } from "@/src/lib/firebase/admin";
import { emptyVendorProfile, vendorProfileCompleteness } from "@/src/lib/firebase/vendor-profiles";
import { VendorMediaUploader } from "@/src/components/firebase-platform/vendor-media-uploader";

const field="min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-base outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100";
const lines=(value?:readonly string[])=>value?.join("\n")??"";

export async function FirebaseVendorProfileEditor({user,organization,result}:{user:AppUser;organization:Membership;result?:string}){
  const db=getPlatformFirestore();
  const [organizationSnapshot,profileSnapshot]=await Promise.all([db.doc(`organizations/${organization.organizationId}`).get(),db.doc(`vendorProfiles/${organization.organizationId}`).get()]);
  const profile=(profileSnapshot.data() as VendorProfileDocument|undefined)??emptyVendorProfile({organizationId:organization.organizationId,businessName:organizationSnapshot.data()?.name??organization.organizationName});
  const completeness=vendorProfileCompleteness(profile);
  return <div><Link href="/vendor" className="inline-flex items-center text-sm font-bold text-slate-500"><ArrowLeft className="mr-2 size-4"/>Vendor dashboard</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_18rem]"><main className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Firebase vendor profile</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Complete your marketplace profile.</h1><p className="mt-4 text-sm leading-6 text-slate-600">Saving changes unpublishes the projection until administrator review. Payment alone never publishes a listing.</p>{result?<p role="status" className={`mt-5 rounded-xl p-4 text-sm font-semibold ${result==="saved"?"bg-emerald-50 text-emerald-800":"bg-rose-50 text-rose-800"}`}>{result==="saved"?"Profile saved for review.":"Review the fields and try again."}</p>:null}<section className="mt-7 grid gap-4 sm:grid-cols-2"><VendorMediaUploader organizationId={organization.organizationId} assetKind="logo" currentUrl={profile.media.logoUrl}/><VendorMediaUploader organizationId={organization.organizationId} assetKind="featured" currentUrl={profile.media.featuredImageUrl}/></section><form action={saveVendorProfile} className="mt-8 grid gap-5 sm:grid-cols-2">
    <label className="sm:col-span-2">Business name<input className={field} name="businessName" required defaultValue={profile.businessName}/></label>
    <label className="sm:col-span-2">Description<textarea className={`${field} min-h-32 py-3`} name="description" required minLength={40} defaultValue={profile.description}/></label>
    <label>Public email<input className={field} name="publicEmail" type="email" required defaultValue={profile.publicEmail??user.email}/></label><label>Public phone<input className={field} name="phone" required defaultValue={profile.publicPhone??""}/></label>
    <label>Website<input className={field} name="website" type="url" defaultValue={profile.websiteUrl??""}/></label><label>Google Business Profile<input className={field} name="googleBusinessProfileUrl" type="url" defaultValue={profile.googleBusinessProfileUrl??""}/></label>
    <label>Primary category<input className={field} name="primaryCategory" required defaultValue={profile.primaryCategorySlug}/></label><label>Additional categories<textarea className={`${field} min-h-24 py-3`} name="additionalCategories" defaultValue={lines(profile.additionalCategorySlugs)}/></label>
    <label>Services<textarea className={`${field} min-h-32 py-3`} name="services" required defaultValue={lines(profile.services)}/></label><label>Service areas<textarea className={`${field} min-h-32 py-3`} name="serviceAreas" required defaultValue={lines(profile.serviceAreaKeys)}/></label>
    <label>Service radius (miles)<input className={field} name="serviceRadiusMiles" type="number" min="1" max="500" defaultValue={profile.serviceRadiusMiles??""}/></label><label>Years in business<input className={field} name="yearsInBusiness" type="number" min="0" max="250" defaultValue={profile.yearsInBusiness??""}/></label>
    <label>Hours<textarea className={`${field} min-h-24 py-3`} name="operatingHours" defaultValue={profile.operatingHours??""}/></label><label>Languages<textarea className={`${field} min-h-24 py-3`} name="languages" defaultValue={lines(profile.languages)}/></label>
    <label>Customer types<textarea className={`${field} min-h-24 py-3`} name="customerTypes" defaultValue={lines(profile.customerTypes)}/></label><label>Insurance<select className={field} name="insuranceStatus" defaultValue={profile.insurance.status}><option value="unknown">Unknown</option><option value="insured">Insured</option><option value="not_insured">Not insured</option><option value="expired">Expired</option></select></label>
    <label><input name="licenseApplies" type="checkbox" defaultChecked={profile.license.applies}/> License applies<input className={field} name="licenseNumber" placeholder="License number" defaultValue={profile.license.number??""}/></label><label>License jurisdiction<input className={field} name="licenseJurisdiction" defaultValue={profile.license.jurisdiction??""}/></label>
    <div className="grid gap-2 rounded-xl bg-slate-50 p-4 sm:col-span-2"><label><input name="offersFreeEstimates" type="checkbox" defaultChecked={profile.offersFreeEstimates}/> Free estimates</label><label><input name="offersFinancing" type="checkbox" defaultChecked={profile.offersFinancing}/> Financing</label><label><input name="emergencyService" type="checkbox" defaultChecked={profile.emergencyService}/> Emergency service</label></div>
    <div className="grid gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 sm:col-span-2"><label><input name="connectMemberBenefitEnabled" type="checkbox" defaultChecked={profile.connectMemberBenefit.enabled}/> Connect Member Benefit</label><input className={field} name="connectMemberBenefitTitle" placeholder="Benefit title" defaultValue={profile.connectMemberBenefit.title??""}/><textarea className={`${field} min-h-20 py-3`} name="connectMemberBenefitDescription" placeholder="Benefit description" defaultValue={profile.connectMemberBenefit.description??""}/><input className={field} name="connectMemberBenefitType" placeholder="Benefit type" defaultValue={profile.connectMemberBenefit.type??""}/><textarea className={`${field} min-h-20 py-3`} name="connectMemberBenefitTerms" placeholder="Terms" defaultValue={profile.connectMemberBenefit.terms??""}/></div>
    <label className="flex gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:col-span-2"><input name="publicDisplayConsent" type="checkbox" defaultChecked={profile.publicDisplayConsent}/><span>I authorize display of approved public profile information.</span></label><button className="min-h-12 rounded-full bg-slate-950 px-6 text-sm font-black text-white sm:col-span-2">Save for review</button>
  </form></main><aside className="rounded-2xl bg-slate-950 p-6 text-white lg:self-start"><ClipboardCheck className="size-6 text-emerald-400"/><h2 className="mt-5 font-bold">Profile readiness</h2><p className="mt-3 text-3xl font-bold">{completeness.completed}/{completeness.total}</p><p className="mt-2 text-xs text-slate-400">Approval: {profile.approvalState}<br/>Publication: {profile.publicationState}</p>{completeness.missing.length?<p className="mt-4 text-xs leading-5 text-slate-300">Missing: {completeness.missing.join(", ").replaceAll("_"," ")}</p>:null}</aside></div></div>;
}
