import Link from "next/link";
import { PageHeader } from "@/src/components/ui/page-header";
import { FOUNDER_CATEGORY_CATALOG } from "@/src/domain/founder-categories/catalog";
import { requireUser } from "@/src/lib/auth/session";
import { authorize } from "@/src/lib/auth/authorization";
import { isFirebaseOperationalBackend } from "@/src/lib/firebase/platform";
import { listFirebaseProperties } from "@/src/lib/firebase/properties";
import { listFirebaseServiceRequestsForPm } from "@/src/lib/firebase/service-requests";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";
import { createPropertyManagerServiceRequest } from "./actions";

const input="mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-base";
export default async function PropertyManagerServiceRequestsPage(){
  const user=await requireUser();const membership=user.memberships.find(item=>item.organizationType==="property_management");if(!membership)return null;authorize(user,"service_requests:create",membership.organizationId);
  if(isFirebaseOperationalBackend()){
    const [properties,requests]=await Promise.all([listFirebaseProperties(user,membership.organizationId),listFirebaseServiceRequestsForPm(user,membership.organizationId)]);
    return <div><PageHeader eyebrow="Property manager" title="Service requests" description="Submit a service need for review and rule-based Connect Match."/>{requests.length?<div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white">{requests.map(request=><Link key={request.id} href={`/property-manager/service-requests/${request.id}`} className="flex items-center justify-between border-b border-slate-100 p-4 hover:bg-slate-50"><p className="font-bold">{request.propertyName} · {request.categoryName}</p><span className="text-xs font-bold capitalize text-slate-500">{request.status.replaceAll("_"," ")}</span></Link>)}</div>:null}<form action={createPropertyManagerServiceRequest} className="mt-8 grid max-w-4xl gap-4 rounded-2xl border border-slate-200 bg-white p-6 sm:grid-cols-2"><input type="hidden" name="organizationId" value={membership.organizationId}/><label>Property<select className={input} name="propertyId" required defaultValue=""><option value="" disabled>Select property</option>{properties.map(property=><option key={property.id} value={property.id}>{String(property.name)}</option>)}</select></label><label>Category<select className={input} name="vendorCategoryId" required defaultValue=""><option value="" disabled>Select category</option>{FOUNDER_CATEGORY_CATALOG.map(category=><option key={category.slug} value={category.slug}>{category.displayName}</option>)}</select></label><label>Unit<input className={input} name="unit"/></label><label>Contact name<input className={input} name="contactName" defaultValue={user.fullName??""} required/></label><label className="sm:col-span-2">Problem description<textarea className={`${input} min-h-28 py-2`} name="problemDescription" required/></label><label>Priority<select className={input} name="priority"><option value="emergency">Emergency</option><option value="today">Today</option><option value="this_week">This week</option><option value="flexible">Flexible</option></select></label><label>Preferred contact<select className={input} name="preferredContact"><option value="phone">Phone</option><option value="email">Email</option></select></label><label>Phone<input className={input} name="phone"/></label><label>Email<input className={input} name="email" type="email" defaultValue={user.email}/></label><label className="sm:col-span-2">Access instructions<textarea className={`${input} min-h-20 py-2`} name="accessInstructions"/></label><button className="min-h-11 rounded-full bg-slate-950 px-6 text-sm font-bold text-white sm:col-span-2">Submit service request</button></form></div>;
  }
  const db=await createSupabaseServerClient();const [{data:properties},{data:categories},{data:requests}]=await Promise.all([db.from("properties").select("id,name").eq("organization_id",membership.organizationId).eq("status","active").order("name"),db.from("vendor_categories").select("id,name").eq("is_active",true).order("sort_order"),db.from("property_manager_service_requests").select("id,status").eq("organization_id",membership.organizationId)]);
  return <div><PageHeader eyebrow="Property manager" title="Service requests" description="Submit a service need for administrator review."/>{requests?.map(item=><p key={item.id}>{item.status}</p>)}<form action={createPropertyManagerServiceRequest} className="mt-8 grid gap-4"><input type="hidden" name="organizationId" value={membership.organizationId}/><select name="propertyId">{properties?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="vendorCategoryId">{categories?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="address" defaultValue="Property address"/><textarea name="problemDescription" defaultValue="Describe the service request"/><select name="priority"><option value="flexible">Flexible</option></select><select name="preferredContact"><option value="email">Email</option></select><input name="email" defaultValue={user.email}/><button>Submit</button></form></div>;
}
