import { adminCreateServiceRequest, managePropertyManagerServiceRequest } from "./actions";
import { requireUser } from "@/src/lib/auth/session";
import { createSupabaseAdminClient } from "@/src/lib/supabase/admin";
import { requestCounts } from "@/src/domain/property-manager-requests/catalog";

const input = "min-h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm";

export default async function AdminServiceRequestsPage() {
  const user = await requireUser(); if (!user.isSuperAdmin) throw new Error("Super Admin access required.");
  const db = createSupabaseAdminClient();
  const [{ data: requests }, { data: vendors }, { data: categories }, { data: managers }] = await Promise.all([
    db.from("property_manager_service_requests").select("*,properties(name),vendor_categories(name),organizations(name)").order("created_at", { ascending: false }),
    db.from("vendor_category_assignments").select("vendor_organization_id,vendor_category_id,organizations(name)"),
    db.from("vendor_categories").select("id,name").eq("is_active", true).order("sort_order"),
    db.from("organizations").select("id,name").eq("type", "property_management").order("name"),
  ]);
  const rows = requests ?? []; const counts = requestCounts(rows);
  return <div><p className="text-sm font-semibold text-emerald-700">Manual request oversight</p><h1 className="mt-1 text-4xl font-semibold">Service Requests</h1>
    <details className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-bold">Quick-create opportunity</summary><form action={adminCreateServiceRequest} className="mt-5 grid gap-3 sm:grid-cols-2"><select className={input} name="organizationId" required defaultValue=""><option value="" disabled>Property manager</option>{managers?.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={input} name="propertyName" placeholder="Property or building name" required/><input className={input} name="address" placeholder="Address" required/><input className={input} name="city" placeholder="City" required/><input className={input} name="unit" placeholder="Unit (optional)"/><select className={input} name="categoryId">{categories?.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={input} name="priority"><option value="emergency">Emergency</option><option value="today">Today</option><option value="this_week">This Week</option><option value="flexible">Flexible</option></select><input className={input} name="contactName" placeholder="Property-manager contact name" required/><input className={input} name="phone" placeholder="Phone"/><input className={input} name="email" placeholder="Email"/><textarea className={`${input} min-h-24 sm:col-span-2`} name="description" placeholder="Problem description" required/><textarea className={`${input} sm:col-span-2`} name="vendorNotes" placeholder="Vendor-visible notes"/><textarea className={`${input} sm:col-span-2`} name="internalNotes" placeholder="Internal admin notes"/><label className="text-sm sm:col-span-2"><input type="checkbox" name="share" value="yes" required/> Permission confirmed to share request with matched vendors</label><button className="min-h-11 rounded-xl bg-slate-950 text-sm font-bold text-white sm:col-span-2">Create request</button></form></details>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(counts).map(([k,v]) => <div key={k} className="rounded-xl border bg-white p-4"><p className="text-xs capitalize text-slate-500">{k}</p><p className="text-2xl font-bold">{v}</p></div>)}</section>
    <div className="mt-6 grid gap-3">{rows.map(r => { const matches=(vendors??[]).filter(v=>v.vendor_category_id===r.vendor_category_id); return <details key={r.id} className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">{(r.properties as unknown as {name:string}|null)?.name ?? r.manual_property_name ?? "Property"} · {(r.vendor_categories as unknown as {name:string}|null)?.name} · {r.status}</summary><p className="mt-3 text-sm">{r.problem_description}</p><p className="mt-2 text-xs text-slate-500">Source: {r.request_source} · Internal notes are admin-only.</p><form action={managePropertyManagerServiceRequest} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="requestId" value={r.id}/><select className={input} name="vendorId" defaultValue={r.assigned_vendor_organization_id??""}><option value="">Assign matching vendor</option>{matches.map(v=><option key={v.vendor_organization_id} value={v.vendor_organization_id}>{(v.organizations as unknown as {name:string}|null)?.name}</option>)}</select><select className={input} name="status" defaultValue={r.status==="submitted"?"reviewing":r.status}><option value="reviewing">Reviewing</option><option value="assigned">Assigned</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><input className={input} name="note" placeholder="Timeline note"/><button className="rounded-xl bg-slate-950 px-4 text-xs font-bold text-white">Save</button></form>{r.assigned_vendor_organization_id?<p className="mt-3 rounded-lg bg-emerald-50 p-3 text-xs">New Optimize Local Connect opportunity assigned to your account: https://www.optimizelocalai.com/vendor/opportunities</p>:null}</details> })}</div>
  </div>;
}
