import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Award, BadgeCheck, Clock3, ExternalLink, Globe2, Languages, Mail, MapPin, Phone, ShieldCheck, Siren, Store } from "lucide-react";
import { notFound } from "next/navigation";
import { FoundingPartnerLogo } from "@/src/components/marketplace/founding-partner-logo";
import { PublicMarketplaceShell } from "@/src/components/marketplace/public-marketplace-shell";
import { parsePublicFoundingPartnerProfile, type PublicFoundingPartnerProfile } from "@/src/domain/vendor-memberships/marketplace";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ slug: string }> };
function safeUrl(value: string | null) { return value && /^https?:\/\//i.test(value) ? value : null; }
function statusLabel(value: string | null) { return value ? value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase()) : "Not provided"; }

async function getProfile(slug: string): Promise<PublicFoundingPartnerProfile | null> {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return null;
  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.rpc("get_public_vendor_profile", { target_slug: slug });
  if (error || !data) return null;
  const parsed = parsePublicFoundingPartnerProfile(data);
  return parsed.publicDisplayConsent ? parsed : null;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const profile = await getProfile(slug);
  if (!profile) return { title: "Vendor Not Found", robots: { index: false, follow: false } };
  const description = `${profile.name} provides ${profile.primaryCategory.toLowerCase()} services across ${profile.serviceAreas.slice(0, 3).join(", ")}.`;
  return { title: `${profile.name} | Local Vendor`, description, alternates: { canonical: `/marketplace/${profile.slug}` }, openGraph: { title: `${profile.name} | Optimize Local Connect`, description, url: `/marketplace/${profile.slug}`, type: "profile", images: safeUrl(profile.featuredImageUrl) ? [{ url: profile.featuredImageUrl! }] : safeUrl(profile.logoUrl) ? [{ url: profile.logoUrl! }] : undefined } };
}

export default async function PublicVendorProfilePage({ params }: Props) {
  const { slug } = await params;
  const profile = await getProfile(slug);
  if (!profile) notFound();
  const categories = [...new Set([profile.primaryCategory, ...profile.additionalCategories])];

  return <PublicMarketplaceShell><div className="mx-auto max-w-[90rem] px-5 py-8 sm:px-8 sm:py-12 lg:px-12">
    <Link href="/marketplace" className="inline-flex items-center text-sm font-bold text-slate-500 hover:text-slate-950"><ArrowLeft className="mr-2 size-4" />Back to marketplace</Link>
    <section className="relative mt-6 overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white sm:p-10"><div aria-hidden="true" className="absolute -right-28 -top-32 size-96 rounded-full border-[65px] border-emerald-400/5" /><div className="relative flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><FoundingPartnerLogo src={profile.logoUrl} name={profile.name} size="profile" /><div>{profile.badgeLabel?<span className="inline-flex items-center gap-1.5 rounded-full bg-amber-300/15 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.12em] text-amber-200"><Award className="size-3.5" />{profile.badgeLabel}</span>:null}<h1 className="mt-4 text-4xl font-semibold leading-none tracking-[-.05em] sm:text-6xl">{profile.name}</h1><p className="mt-4 text-sm font-bold text-emerald-300">{profile.primaryCategory} · {profile.membershipName}</p></div></div><div className="flex flex-col gap-3 sm:flex-row"><a href={`mailto:${profile.email}`} className="inline-flex min-h-12 items-center justify-center rounded-full bg-emerald-400 px-6 text-sm font-black text-emerald-950 hover:bg-emerald-300"><Mail className="mr-2 size-4" />Email vendor</a>{profile.phone ? <a href={`tel:${profile.phone}`} className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/20 px-6 text-sm font-bold hover:bg-white/10"><Phone className="mr-2 size-4" />Call {profile.phone}</a> : null}</div></div></section>

    <div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><main className="space-y-6">
      {profile.propertyManagerPerk ? <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.14em] text-amber-700">Property Manager Perk</p><h2 className="mt-3 text-2xl font-bold text-amber-950">{profile.propertyManagerPerk.title}</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-amber-900/75">{profile.propertyManagerPerk.description}</p>{profile.propertyManagerPerk.terms ? <p className="mt-4 border-t border-amber-200 pt-4 text-xs leading-5 text-amber-900/65"><strong>Terms:</strong> {profile.propertyManagerPerk.terms}</p> : null}{profile.propertyManagerPerk.expirationDate ? <p className="mt-2 text-xs text-amber-900/65">Available through {new Date(`${profile.propertyManagerPerk.expirationDate}T12:00:00`).toLocaleDateString()}</p> : null}</section> : null}
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">About {profile.name}</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{profile.description}</p><div className="mt-5 flex flex-wrap gap-2">{categories.map((name, index) => <Link key={name} href={index === 0 ? `/marketplace/category/${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}` : `/marketplace?q=${encodeURIComponent(name)}`} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600 hover:bg-emerald-50 hover:text-emerald-800">{name}</Link>)}</div><div className="mt-6 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Years in business</p><p className="mt-1 text-lg font-bold">{profile.yearsInBusiness ?? "Not provided"}</p></div><div><p className="text-xs text-slate-400">Customer type</p><p className="mt-1 text-lg font-bold">{statusLabel(profile.customerType)}</p></div><div><p className="text-xs text-slate-400">Languages</p><p className="mt-1 text-lg font-bold">{profile.languagesSpoken.join(", ")}</p></div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Store className="size-5 text-emerald-700" /><h2 className="text-xl font-bold">Services offered</h2></div>{profile.servicesOffered.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{profile.servicesOffered.map(service => <div key={service} className="rounded-xl bg-slate-50 p-4 text-sm font-bold text-slate-700">{service}</div>)}</div> : <p className="mt-4 text-sm text-slate-500">Contact the business for its current service list.</p>}<div className="mt-5 flex flex-wrap gap-2">{profile.offersFreeEstimates ? <span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-800">Free estimates available</span> : null}{profile.offersFinancing ? <span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-800">Financing options available</span> : null}{profile.emergencyAvailable ? <span className="inline-flex items-center gap-1.5 rounded-full bg-rose-50 px-3 py-1.5 text-xs font-bold text-rose-700"><Siren className="size-3.5" />Emergency service available</span> : null}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><MapPin className="size-5 text-emerald-700" /><h2 className="text-xl font-bold">Service areas</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{profile.serviceAreas.map(area => <Link key={area} href={`/marketplace?location=${encodeURIComponent(area)}`} className="flex items-center gap-2 rounded-xl bg-slate-50 p-4 text-sm font-bold text-slate-700 hover:bg-emerald-50"><MapPin className="size-4 text-emerald-700" />{area}</Link>)}</div>{profile.serviceRadiusMiles != null ? <p className="mt-4 text-xs text-slate-500">Typical service radius: {profile.serviceRadiusMiles} miles. Confirm availability directly for a specific address.</p> : null}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-emerald-700" /><h2 className="text-xl font-bold">Business information</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">License</p><p className="mt-1 font-bold">{profile.licenseApplicable ? profile.licenseNumber || "Applicable—number not displayed" : "Not applicable for this listing"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Insurance status</p><p className="mt-1 font-bold">{statusLabel(profile.insuranceStatus)}</p></div></div><p className="mt-4 text-xs leading-5 text-slate-400">Credential information is business-submitted. Founding Partner status does not guarantee licensing, insurance, leads, or work quality. Verify requirements directly before hiring.</p></section>
    </main>
    <aside className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Contact and hours</h2><div className="mt-5 space-y-4 text-sm">{profile.phone ? <a href={`tel:${profile.phone}`} className="flex items-start gap-3 text-slate-700 hover:text-emerald-700"><Phone className="mt-0.5 size-4 shrink-0 text-emerald-700" /><span><span className="block text-xs text-slate-400">Phone</span><strong className="mt-1 block">{profile.phone}</strong></span></a> : null}<a href={`mailto:${profile.email}`} className="flex items-start gap-3 text-slate-700 hover:text-emerald-700"><Mail className="mt-0.5 size-4 shrink-0 text-emerald-700" /><span className="min-w-0"><span className="block text-xs text-slate-400">Email</span><strong className="mt-1 block break-all">{profile.email}</strong></span></a>{profile.operatingHours ? <p className="flex items-start gap-3"><Clock3 className="mt-0.5 size-4 shrink-0 text-emerald-700" /><span><span className="block text-xs text-slate-400">Typical hours</span><strong className="mt-1 block">{profile.operatingHours}</strong></span></p> : null}<p className="flex items-start gap-3"><Languages className="mt-0.5 size-4 shrink-0 text-emerald-700" /><span><span className="block text-xs text-slate-400">Languages</span><strong className="mt-1 block">{profile.languagesSpoken.join(", ")}</strong></span></p></div><div className="mt-6 grid gap-2">{safeUrl(profile.website) ? <a href={profile.website!} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center rounded-full bg-slate-950 px-4 text-sm font-bold text-white hover:bg-emerald-700"><Globe2 className="mr-2 size-4" />Business website</a> : null}{safeUrl(profile.googleBusinessProfileUrl) ? <a href={profile.googleBusinessProfileUrl!} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center rounded-full border border-slate-200 px-4 text-sm font-bold text-slate-700 hover:bg-slate-50"><BadgeCheck className="mr-2 size-4 text-emerald-700" />Google Business Profile</a> : null}</div></section>
      {profile.badgeLabel?<section className="rounded-2xl bg-amber-50 p-6"><Award className="size-6 text-amber-700" /><h2 className="mt-5 font-bold text-amber-950">{profile.badgeLabel}</h2><p className="mt-2 text-sm leading-6 text-amber-900/75">This business has an approved, active {profile.membershipName} marketplace profile.</p></section>:null}
      {safeUrl(profile.featuredImageUrl) ? <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={profile.featuredImageUrl!} alt={`${profile.name} business`} className="aspect-[4/3] w-full object-cover" />
      </section> : null}
      <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="font-bold text-emerald-950">Ready to discuss a job?</h2><p className="mt-2 text-sm leading-6 text-emerald-900/75">Contact the vendor directly to confirm scope, availability, pricing, and credentials.</p><a href={`mailto:${profile.email}?subject=${encodeURIComponent(`Service inquiry from Optimize Local Connect`)}`} className="mt-5 inline-flex min-h-11 w-full items-center justify-center rounded-full bg-emerald-700 px-4 text-sm font-black text-white hover:bg-emerald-800">Contact {profile.name} <ExternalLink className="ml-2 size-4" /></a></section>
    </aside></div>
  </div></PublicMarketplaceShell>;
}
