import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Award, BadgeCheck, CalendarCheck, Clock3, MapPin, ShieldCheck, Star } from "lucide-react";
import { notFound } from "next/navigation";
import { createSupabaseServerClient } from "@/src/lib/supabase/server";

type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase.from("organizations").select("name").eq("slug", slug).eq("type", "vendor").maybeSingle();
  return { title: data?.name ? `${data.name} | Local Marketplace` : "Local Provider Profile", description: data?.name ? `Explore ${data.name}'s services, coverage, credentials, and local performance.` : "Trusted local provider profile." };
}

export default async function VendorProfilePage({ params }: Props) {
  const { slug } = await params;
  const supabase = await createSupabaseServerClient();
  const { data: organization } = await supabase.from("organizations").select("id,name,slug,website_url,phone").eq("slug", slug).eq("type", "vendor").eq("status", "active").maybeSingle();
  if (!organization) notFound();

  const [{ data: profile }, { data: categories }, { data: services }, { data: cities }, { data: badges }, { data: reviews }, { data: media }] = await Promise.all([
    supabase.from("vendor_profiles").select("description,years_in_business,average_rating,completed_job_count,response_time_minutes,verification_status").eq("organization_id", organization.id).maybeSingle(),
    supabase.from("vendor_category_assignments").select("vendor_categories(name)").eq("vendor_organization_id", organization.id),
    supabase.from("vendor_service_offerings").select("emergency_available,vendor_services(name,description)").eq("vendor_organization_id", organization.id).eq("is_active", true),
    supabase.from("vendor_service_cities").select("cities(name,state_code)").eq("vendor_organization_id", organization.id).eq("is_active", true),
    supabase.from("vendor_badge_awards").select("vendor_badges(name,code)").eq("vendor_organization_id", organization.id).is("revoked_at", null).order("awarded_at", { ascending: false }),
    supabase.from("vendor_reviews").select("id,rating,title,body,published_at").eq("vendor_organization_id", organization.id).eq("status", "published").order("published_at", { ascending: false }).limit(6),
    supabase.from("vendor_marketplace_media").select("id,media_type,external_url,title,alt_text").eq("vendor_organization_id", organization.id).eq("is_published", true).order("sort_order").limit(12),
  ]);

  const profileData = profile as { description: string | null; years_in_business: number | null; average_rating: number | null; completed_job_count: number; response_time_minutes: number | null; verification_status: string } | null;
  const categoryNames = (categories ?? []).map((row) => (row.vendor_categories as unknown as { name: string } | null)?.name).filter(Boolean) as string[];
  const serviceRows = (services ?? []).map((row) => ({ ...(row.vendor_services as unknown as { name: string; description: string | null } | null), emergency: row.emergency_available })).filter((row) => row.name);
  const cityRows = (cities ?? []).map((row) => row.cities as unknown as { name: string; state_code: string } | null).filter(Boolean) as { name: string; state_code: string }[];
  const badgeRows = (badges ?? []).map((row) => row.vendor_badges as unknown as { name: string; code: string } | null).filter(Boolean) as { name: string; code: string }[];

  return <div>
    <Link href="/marketplace" className="inline-flex items-center text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft className="mr-2 size-4" />Back to marketplace</Link>
    <section className="mt-6 overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white sm:p-10">
      <div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div className="flex items-start gap-4"><span className="grid size-16 shrink-0 place-items-center rounded-2xl bg-emerald-400 text-xl font-black text-emerald-950">{organization.name.split(/\s+/).slice(0, 2).map((word: string) => word[0]).join("").toUpperCase()}</span><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-400">Trusted local provider</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">{organization.name}</h1><div className="mt-4 flex flex-wrap gap-2">{profileData?.verification_status === "verified" ? <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-400/15 px-3 py-1.5 text-xs font-bold text-emerald-300"><BadgeCheck className="size-3.5" />Verified credentials</span> : null}{badgeRows.map((badge) => <span key={badge.code} className="inline-flex items-center gap-1.5 rounded-full bg-amber-300/15 px-3 py-1.5 text-xs font-bold text-amber-200"><Award className="size-3.5" />{badge.name}</span>)}</div></div></div><div className="flex flex-col gap-3 sm:flex-row"><Link href={`/requests/new?vendor=${organization.id}`} className="inline-flex min-h-12 items-center justify-center rounded-full bg-emerald-400 px-6 text-sm font-black text-emerald-950 hover:bg-emerald-300"><CalendarCheck className="mr-2 size-4" />Request a quote</Link>{organization.phone ? <a href={`tel:${organization.phone}`} className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/20 px-6 text-sm font-bold text-white hover:bg-white/10">Contact provider</a> : null}</div></div>
    </section>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><main className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">About {organization.name}</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{profileData?.description || "This provider has not published a description yet."}</p>{categoryNames.length ? <div className="mt-5 flex flex-wrap gap-2">{categoryNames.map((name) => <span key={name} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600">{name}</span>)}</div> : null}<div className="mt-6 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Years in business</p><p className="mt-1 text-lg font-bold">{profileData?.years_in_business ?? "Not provided"}</p></div><div><p className="text-xs text-slate-400">Completed jobs</p><p className="mt-1 text-lg font-bold">{profileData?.completed_job_count?.toLocaleString() ?? "Not provided"}</p></div><div><p className="text-xs text-slate-400">Response time</p><p className="mt-1 flex items-center gap-1.5 text-lg font-bold"><Clock3 className="size-4 text-emerald-700" />{profileData?.response_time_minutes != null ? `${profileData.response_time_minutes} min` : "Not provided"}</p></div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Services</h2>{serviceRows.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{serviceRows.map((service) => <article key={service.name} className="rounded-xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{service.name}</h3>{service.emergency ? <span className="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-black uppercase text-rose-700">Emergency</span> : null}</div>{service.description ? <p className="mt-2 text-xs leading-5 text-slate-500">{service.description}</p> : null}</article>)}</div> : <p className="mt-4 text-sm text-slate-500">Services will appear here as this provider completes their profile.</p>}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Reviews</h2>{reviews?.length ? <div className="mt-5 space-y-4">{reviews.map((review) => <article key={review.id} className="border-b border-slate-100 pb-4 last:border-0 last:pb-0"><div className="flex items-center gap-2"><span className="flex items-center gap-1 text-sm font-black"><Star className="size-4 fill-amber-400 text-amber-400" />{review.rating}/5</span>{review.title ? <span className="font-bold">{review.title}</span> : null}</div>{review.body ? <p className="mt-2 text-sm leading-6 text-slate-600">{review.body}</p> : null}</article>)}</div> : <p className="mt-4 text-sm text-slate-500">No published reviews yet. Reviews appear after completed, verified work.</p>}</section></main>
      <aside className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold">Coverage</h2>{cityRows.length ? <div className="mt-4 space-y-2">{cityRows.map((city) => <p key={`${city.name}-${city.state_code}`} className="flex items-center gap-2 text-sm text-slate-600"><MapPin className="size-4 text-emerald-700" />{city.name}, {city.state_code}</p>)}</div> : <p className="mt-4 text-sm text-slate-500">Coverage area not provided yet.</p>}{organization.website_url ? <a href={organization.website_url} target="_blank" rel="noreferrer" className="mt-5 inline-flex text-sm font-bold text-emerald-700 hover:text-emerald-900">Visit website →</a> : null}</section><section className="rounded-2xl bg-emerald-50 p-6"><ShieldCheck className="size-6 text-emerald-700"/><h2 className="mt-5 font-bold">Make a confident decision</h2><p className="mt-2 text-sm leading-6 text-emerald-900/75">Credentials, reviews, response history, and coverage are shown from governed Connect records.</p><Link href={`/requests/new?vendor=${organization.id}`} className="mt-5 inline-flex min-h-11 w-full items-center justify-center rounded-full bg-slate-950 px-4 text-sm font-bold text-white hover:bg-emerald-700">Request service</Link></section>{media?.length ? <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold">Gallery</h2><div className="mt-4 grid grid-cols-2 gap-2">{media.map((item) => item.external_url ? <img key={item.id} src={item.external_url} alt={item.alt_text || item.title || "Provider work"} className="aspect-square w-full rounded-xl object-cover" /> : null)}</div></section> : null}</aside>
    </div>
  </div>;
}
