import Link from "next/link";
import {
  ArrowRight,
  BadgeCheck,
  Banknote,
  BellRing,
  Building2,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleDollarSign,
  Clock3,
  MapPin,
  MessageSquareText,
  PackageCheck,
  ShieldCheck,
  Sparkles,
  SprayCan,
  Store,
  TimerReset,
  Users,
  WashingMachine,
  Wrench,
  Zap,
} from "lucide-react";
import { Logo } from "@/src/components/brand/logo";
import { PLATFORM_BRAND } from "@/src/domain/platform/brand";
import { FOUNDING_PARTNER_PLAN, formatVendorPlanPrice } from "@/src/domain/vendor-memberships/catalog";

const founderPrice = formatVendorPlanPrice(FOUNDING_PARTNER_PLAN);

const steps = [
  { number: "01", title: "Tell us what you need", copy: "Add the property, explain the problem, and attach a photo if it helps.", icon: MessageSquareText },
  { number: "02", title: "Pick a trusted provider", copy: "See local providers, their services, and their credentials in one place.", icon: MapPin },
  { number: "03", title: "Choose a quote", copy: "Compare your options and approve the work when you are ready.", icon: CheckCircle2 },
  { number: "04", title: "Track it to done", copy: "Follow updates, keep the records, and know what happened next.", icon: PackageCheck },
];

const services = [
  { id: "cleaning", eyebrow: "Turn-ready cleaning", title: "Every clean, scoped and accountable.", copy: "Schedule recurring, move-out, deep, and common-area cleaning with room-level details and photo proof of completion.", icon: SprayCan, tint: "bg-[#e9f8f1]", ink: "text-emerald-700", details: ["Recurring schedules", "Turn checklists", "Photo documentation"] },
  { id: "appliances", eyebrow: "Appliance services", title: "Know what is installed. Fix it faster.", copy: "Keep model, serial, warranty, and service history connected to every unit—then route repair or replacement to the right technician.", icon: WashingMachine, tint: "bg-[#eef2ff]", ink: "text-indigo-700", details: ["Asset inventory", "Warranty tracking", "Repair history"] },
  { id: "emergency", eyebrow: "Emergency repairs", title: "Urgent work without the scramble.", copy: "Escalate leaks, no-cooling calls, electrical hazards, and lockouts to on-call providers with clear safety status and response tracking.", icon: BellRing, tint: "bg-[#fff1ed]", ink: "text-orange-700", details: ["Priority escalation", "On-call matching", "Live status updates"] },
];

const managerBenefits = [
  { title: "Hours back every week", copy: "Replace calls, texts, spreadsheets, and repeated follow-ups with one shared operating record.", icon: Clock3 },
  { title: "Spend with confidence", copy: "Compare quotes, preserve rate history, and understand cost by property, provider, service, and city.", icon: CircleDollarSign },
  { title: "A stronger provider network", copy: "See credentials, service coverage, responsiveness, ratings, and outcomes before awarding work.", icon: ShieldCheck },
  { title: "Ready for every market", copy: "Standardize the playbook once, then expand into new cities without rebuilding operations.", icon: Building2 },
];

const vendorBenefits = [
  {
    title: "Recurring Property Demand",
    copy: "Rental properties constantly need repairs, maintenance, replacements, cleaning, landscaping, and specialized services.",
    icon: Wrench,
  },
  {
    title: "Direct Property Manager Relationships",
    copy: "Build repeat relationships with local property decision-makers instead of relying on a stream of one-off consumer leads.",
    icon: Users,
  },
  {
    title: "Stand Out With a Property Manager Perk",
    copy: "Feature one exclusive benefit, service commitment, or promotional offer that gives property managers a clear reason to contact you.",
    icon: BadgeCheck,
  },
];

const propertyManagerPerks = [
  "Free initial service call",
  "Free delivery",
  "Priority 24–48-hour scheduling",
  "Percentage off labor",
  "Parts at cost",
  "Free estimates",
  "Multi-property pricing",
  "Dedicated property-manager contact",
];

const plans = [
  { name: "Starter", price: "$0", suffix: "during early access", copy: "For independent managers building a better local provider workflow.", features: ["Up to 25 units", "Local provider marketplace", "Service requests and quotes", "Email support"], featured: false, action: "Join early access" },
  { name: "Portfolio", price: "$149", suffix: "per month", copy: "For growing property teams managing multiple buildings and providers.", features: ["Up to 500 units", "Team roles and approvals", "Provider performance history", "Work orders and invoices", "Priority support"], featured: true, action: "Start with Portfolio" },
  { name: "Enterprise", price: "Let’s talk", suffix: "built around your operation", copy: "For multi-market operators that need governance, integration, and scale.", features: ["Unlimited markets", "Advanced permissions", "Custom integrations", "Data migration support", "Dedicated success lead"], featured: false, action: "Talk to our team" },
];

const faqs = [
  ["Is Optimize Local Connect only for property management?", "No. Property Management is Version 1. HOAs, Homeowners, Realtors, Local Governments, Schools, Healthcare, Nonprofits, and Service Marketplaces are planned on the same shared operating platform."],
  ["Is this just a provider directory?", "No. Optimize Local Connect is a community platform and transactional marketplace: requests, matching, quotes, work orders, invoices, communication, performance, and records stay connected."],
  ["How are local providers verified?", "Verification is designed to include identity, business registration, licensing, insurance, service coverage, and ongoing performance signals. Requirements can vary by service, industry, and market."],
  ["Can our existing providers join?", "Yes. Invite trusted partners into your private network while also discovering qualified local providers when you need more coverage or a new specialty."],
  ["Does it work across multiple cities?", "Yes. Cities, markets, organizations, properties, provider coverage, and access are modeled independently so teams can expand without duplicating systems."],
  ["Can technicians use it from the field?", "Yes. The experience is mobile-first, with role-specific access so technicians can see assignments, update status, and add job documentation without navigating administrative screens."],
  ["When will pricing begin?", "Founding teams receive early-access terms before paid plans begin. Final pricing may evolve with the product, and founding participants will receive advance notice."],
];

function ArrowLink({ href, children, light = false }: { href: string; children: React.ReactNode; light?: boolean }) {
  return <a href={href} className={`group inline-flex min-h-12 items-center justify-center rounded-full px-6 text-sm font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2 ${light ? "bg-white text-slate-950 hover:bg-emerald-50" : "bg-slate-950 text-white shadow-lg shadow-slate-950/10 hover:-translate-y-0.5 hover:bg-emerald-700"}`}>{children}<ArrowRight aria-hidden="true" className="ml-2 size-4 transition-transform group-hover:translate-x-1" /></a>;
}

export default function Home() {
  return <main id="top" className="min-h-dvh overflow-hidden bg-[#f7f8f4] text-slate-950">
    <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-[#f7f8f4]/85 backdrop-blur-xl">
      <div className="mx-auto flex h-18 max-w-[90rem] items-center justify-between px-5 sm:px-8 lg:px-12"><Logo />
        <nav aria-label="Primary navigation" className="hidden items-center gap-7 2xl:flex">
          {[['Home','#top'],['Marketplace','/marketplace'],['For Property Managers','#managers'],['For Vendors','#providers'],['Community Impact','#impact'],['About','/company'],['Sign In','/sign-in']].map(([label, href]) => <a key={href} href={href} className="text-sm font-medium text-slate-600 transition hover:text-slate-950">{label}</a>)}
        </nav>
        <details className="relative 2xl:hidden"><summary className="grid size-11 cursor-pointer list-none place-items-center rounded-xl border border-slate-200 bg-white text-sm font-bold text-slate-700" aria-label="Menu">Menu</summary><nav aria-label="Mobile public navigation" className="absolute right-0 top-13 z-50 w-72 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><a href="#top" className="block rounded-xl px-3 py-3 text-sm font-semibold text-slate-700">Home</a><Link href="/marketplace" className="block rounded-xl px-3 py-3 text-sm font-semibold text-slate-700">Marketplace</Link><a href="#managers" className="block rounded-xl px-3 py-3 text-sm font-semibold text-slate-700">For Property Managers</a><a href="#providers" className="block rounded-xl px-3 py-3 text-sm font-semibold text-slate-700">For Vendors</a><a href="#impact" className="block rounded-xl px-3 py-3 text-sm font-semibold text-slate-700">Community Impact</a><Link href="/company" className="block rounded-xl px-3 py-3 text-sm font-semibold text-slate-700">About</Link><Link href="/sign-in" className="block rounded-xl px-3 py-3 text-sm font-semibold text-slate-700">Sign In</Link><Link href="/founders" className="mt-1 flex min-h-11 items-center justify-center rounded-xl bg-slate-950 px-3 text-sm font-black text-white">Founding Partner — {founderPrice}</Link></nav></details><div className="hidden items-center gap-2 sm:flex"><Link href="/sign-in" className="inline-flex min-h-11 items-center rounded-full px-4 text-sm font-semibold text-slate-700 hover:bg-white">Sign in</Link><Link href="/founders" className="inline-flex min-h-11 items-center rounded-full bg-slate-950 px-5 text-sm font-semibold text-white transition hover:bg-emerald-700">Founding Partner — {founderPrice}</Link></div>
      </div>
    </header>

    <section className="relative isolate">
      <div aria-hidden="true" className="hero-orb hero-orb-one" /><div aria-hidden="true" className="hero-orb hero-orb-two" />
      <div className="mx-auto grid min-h-[calc(100dvh-4.5rem)] max-w-[90rem] items-center gap-16 px-5 py-16 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:px-12 lg:py-24">
        <div className="relative z-10 max-w-3xl animate-rise">
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-emerald-200/80 bg-white/75 px-3.5 py-2 text-xs font-bold uppercase tracking-[.14em] text-emerald-800 shadow-sm backdrop-blur"><Sparkles className="size-3.5" /> The Rockford Property Service Network</div>
          <h1 className="text-[clamp(2.75rem,4.65vw,5.4rem)] font-semibold leading-[.94] tracking-[-.058em] text-slate-950">Connect With Rockford’s Growing <span className="text-emerald-700">Property Management Network</span></h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">Get your business in front of property managers connected to more than 9,000 rental doors across Rockford and the surrounding area. Build long-term relationships, receive service opportunities, and stand out with an exclusive Property Manager Offer.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><ArrowLink href="/founders">Become a Founding Partner — {founderPrice}</ArrowLink><ArrowLink href="#simple-steps" light>See How It Works</ArrowLink></div>
          <p className="mt-6 flex max-w-2xl items-start gap-2.5 text-sm font-semibold leading-6 text-slate-600"><BadgeCheck aria-hidden="true" className="mt-0.5 size-5 shrink-0 text-emerald-700" />Founding Partners receive premium placement and a verified Founder badge. {founderPrice} is charged today and renews automatically every 12 months until canceled.</p>
        </div>

        <div className="relative mx-auto w-full max-w-2xl animate-rise-delayed lg:mr-0">
          <div className="hero-dashboard relative rounded-[2rem] border border-white/80 bg-white/88 p-3 shadow-[0_40px_120px_rgba(15,23,42,.18)] backdrop-blur-xl sm:p-5">
            <div className="flex items-center justify-between px-2 pb-5 pt-2"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Vendor opportunity</p><p className="mt-1 text-lg font-bold">Built for Rockford property services</p></div><div className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-500">Growing network</div></div>
            <div className="grid grid-cols-3 gap-2 sm:gap-3">{[['9,000+','Rental doors'],['Rockford','Launch market'],[founderPrice,'Annual plan']].map(([value,label]) => <div key={label} className="rounded-2xl bg-slate-50 p-3 sm:p-4"><p className="text-lg font-bold tracking-tight sm:text-2xl">{value}</p><p className="mt-1 text-[10px] text-slate-500 sm:text-xs">{label}</p></div>)}</div>
            <div className="mt-3 rounded-2xl border border-slate-100 bg-white p-4 shadow-[0_8px_30px_rgba(15,23,42,.06)] sm:p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-emerald-50"><Wrench className="size-5 text-emerald-700" /></span><div className="min-w-0"><p className="text-sm font-bold">Build repeat property relationships</p><p className="mt-0.5 text-xs leading-5 text-slate-500">Present your services, coverage area, and one exclusive manager perk.</p></div></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700">Founder</span></div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs font-semibold text-slate-500">Premium placement is subject to profile review and activation.</span><BadgeCheck className="size-4 shrink-0 text-emerald-600" /></div></div>
            <div className="mt-3 grid gap-3 sm:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-400">Impact Engine</p><p className="mt-4 text-2xl font-bold">Measured locally</p><p className="mt-2 text-xs leading-5 text-slate-400">Savings and response metrics appear only when supported by governed records.</p></div><div className="rounded-2xl border border-slate-100 p-4"><p className="text-xs text-slate-500">Optimize AI</p><p className="mt-2 text-2xl font-bold">Every decision</p><p className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><TimerReset className="size-4" /> Evidence first</p></div></div>
          </div>
          <div className="float-card absolute -bottom-7 -left-5 hidden items-center gap-3 rounded-2xl border border-white bg-white p-3.5 shadow-xl sm:flex"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50"><PackageCheck className="size-5 text-emerald-700" /></span><div><p className="text-xs text-slate-500">Work order completed</p><p className="text-sm font-bold">Turn clean · Unit 8B</p></div></div>
        </div>
      </div>
    </section>

    <section id="vendor-benefits" className="border-y border-slate-200 bg-white py-20 sm:py-24"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="max-w-3xl"><p className="section-kicker">Why property-focused vendors join</p><h2 className="section-title">More than another vendor directory.</h2><p className="section-copy">Optimize Local Connect is building a paid local network around the relationships and service standards that keep rental properties operating.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{vendorBenefits.map(({title,copy,icon:Icon},index)=><article key={title} className="rounded-[1.75rem] border border-slate-200 bg-[#fafbf8] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-slate-950"><Icon aria-hidden="true" className="size-5 text-emerald-400" /></span><span className="text-xs font-black text-emerald-700">0{index+1}</span></div><h3 className="mt-10 text-2xl font-bold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{copy}</p>{index===2?<div className="mt-7 border-t border-slate-200 pt-6"><p className="text-xs font-black uppercase tracking-[.14em] text-slate-600">Perk examples</p><div className="mt-4 flex flex-wrap gap-2">{propertyManagerPerks.map(perk=><span key={perk} className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-900">{perk}</span>)}</div></div>:null}</article>)}</div></div></section>

    <section id="simple-steps" className="scroll-reveal bg-[#f7f8f4] py-20 sm:py-28"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="max-w-xl"><p className="section-kicker">How it works</p><h2 className="section-title">Four simple steps.<br />One less thing to chase.</h2><p className="section-copy">You do not need to be technical. If you can send a text, you can use Connect.</p><div id="demo" className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white shadow-xl"><div className="flex aspect-video items-center justify-center rounded-xl border border-white/10 bg-gradient-to-br from-slate-800 to-slate-950"><div className="text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-400 text-emerald-950"><ArrowRight className="ml-1 size-6" /></span><p className="mt-4 text-sm font-bold">Video walkthrough</p><p className="mt-1 text-xs text-slate-400">A short guided demo is coming soon.</p></div></div></div></div><div className="grid gap-3 sm:grid-cols-2">{steps.map(({number,title,copy,icon:Icon}) => <article key={number} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-full bg-emerald-50 text-sm font-black text-emerald-700">{number}</span><Icon className="size-5 text-emerald-700" /></div><h3 className="mt-8 text-xl font-bold tracking-tight">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></div></section>

    <section id="how-it-works" className="scroll-reveal bg-white py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="max-w-3xl"><p className="section-kicker">One community platform</p><h2 className="section-title">Shared foundations.<br />Industry-specific workflows.</h2><p className="section-copy">Identity, organizations, geography, local marketplaces, transactions, communication, analytics, and {PLATFORM_BRAND.aiName} form one reusable platform. Property Management is Version 1.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{steps.map(({number,title,copy,icon:Icon}) => <article key={number} className="group rounded-[1.75rem] border border-slate-200 bg-[#fafbf8] p-6 transition duration-500 hover:-translate-y-1 hover:border-emerald-200 hover:shadow-xl hover:shadow-emerald-950/5 sm:p-8"><div className="flex items-center justify-between"><span className="text-sm font-black text-emerald-700">{number}</span><span className="grid size-11 place-items-center rounded-2xl bg-white shadow-sm"><Icon className="size-5 text-slate-700" /></span></div><h3 className="mt-20 text-2xl font-bold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

    <section id="marketplace" className="scroll-reveal bg-slate-950 py-24 text-white sm:py-32"><div className="mx-auto grid max-w-[90rem] gap-14 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-12"><div><p className="section-kicker text-emerald-400">Local provider marketplace</p><h2 className="section-title text-white">Local expertise.<br />Verified confidence.</h2><p className="section-copy text-slate-400">Find providers by service, city, availability, credentials, and real performance—not whoever happens to answer the phone first.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Verified credentials","City-level coverage","Response history","Transparent quotes"].map(item => <span key={item} className="flex items-center gap-2 text-sm text-slate-300"><Check className="size-4 text-emerald-400" />{item}</span>)}</div><a href="#providers" className="mt-9 inline-flex items-center text-sm font-bold text-emerald-400 hover:text-emerald-300">Explore the founding provider program <ChevronRight className="ml-1 size-4" /></a></div>
      <div className="rounded-[2rem] bg-slate-900 p-6 ring-1 ring-white/10 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Live marketplace standards</p><h3 className="mt-2 text-2xl font-bold">Real businesses. Governed visibility.</h3><div className="mt-7 space-y-3">{[[BadgeCheck,"Verified payment required","Founder payment is confirmed by the payment provider."],[ShieldCheck,"Application review","Profiles are reviewed before public activation."],[MapPin,"Service-area search","Browse actual coverage submitted by active partners."]].map(([Icon,title,copy]) => { const C=Icon as typeof BadgeCheck; return <div key={title as string} className="flex gap-3 rounded-2xl border border-white/5 bg-white/[.025] p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-400/10"><C className="size-4 text-emerald-400" /></span><div><p className="text-sm font-bold">{title as string}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy as string}</p></div></div>})}</div><Link href="/marketplace" className="mt-6 inline-flex min-h-11 items-center rounded-full bg-emerald-400 px-5 text-sm font-black text-emerald-950">Browse active partners <ArrowRight className="ml-2 size-4" /></Link></div>
    </div></section>

    <section id="services" className="bg-[#f7f8f4] py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="max-w-3xl scroll-reveal"><p className="section-kicker">First vertical · Property Management</p><h2 className="section-title">The everyday services that keep communities moving.</h2><p className="section-copy">Purpose-built property workflows run on the same Connect platform that will support future industries.</p></div><div className="mt-14 space-y-5">{services.map(({id,eyebrow,title,copy,icon:Icon,tint,ink,details},index) => <article id={id} key={id} className="scroll-reveal grid overflow-hidden rounded-[2rem] border border-slate-200 bg-white lg:grid-cols-2"><div className={`flex min-h-80 flex-col justify-between p-7 sm:p-10 lg:p-12 ${index%2===1?'lg:order-2':''}`}><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">{eyebrow}</p><h3 className="mt-4 max-w-xl text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">{title}</h3><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">{copy}</p></div><div className="mt-10 flex flex-wrap gap-2">{details.map(detail => <span key={detail} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">{detail}</span>)}</div></div><div className={`grid min-h-80 place-items-center p-8 sm:p-12 ${tint} ${index%2===1?'lg:order-1':''}`}><div className="relative grid size-48 place-items-center rounded-[3rem] bg-white shadow-[0_30px_70px_rgba(15,23,42,.12)] sm:size-60"><div aria-hidden="true" className={`absolute inset-5 rounded-[2.25rem] border border-current opacity-10 ${ink}`} /><Icon className={`size-20 sm:size-24 ${ink}`} strokeWidth={1.25} /><span className="absolute -right-3 -top-3 grid size-14 place-items-center rounded-2xl bg-slate-950 text-white shadow-xl"><Check className="size-6" /></span></div></div></article>)}</div></div></section>

    <section id="network" className="scroll-reveal bg-white py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[1fr_.9fr] lg:items-end"><div className="max-w-4xl"><p className="section-kicker">Expanding through local relationships</p><h2 className="section-title">Connected to Rockford’s broader rental-property network.</h2><p className="section-copy">Our relationships reach across a Rockford-area property-management network representing more than 400 property managers and more than 9,000 rental doors. Optimize Local Connect is the growing platform being built to turn that access into useful, long-term vendor relationships.</p></div><aside className="rounded-[1.75rem] border border-emerald-200 bg-emerald-50 p-7 sm:p-8"><ShieldCheck aria-hidden="true" className="size-7 text-emerald-700" /><p className="mt-7 text-lg font-bold text-emerald-950">Clear about where we are today</p><p className="mt-3 text-sm leading-7 text-emerald-900/75">This is an early Founding Partner opportunity. The broader network is not a claim that every property manager already uses the platform, and service opportunities or revenue are never guaranteed.</p></aside></div></div></section>

    <section id="providers" className="bg-[#dff4e8] py-24 sm:py-32"><div className="mx-auto grid max-w-[90rem] gap-12 px-5 sm:px-8 lg:grid-cols-[1fr_.9fr] lg:items-center lg:px-12"><div className="scroll-reveal"><div className="inline-flex items-center gap-2 rounded-full bg-white/70 px-3.5 py-2 text-xs font-black uppercase tracking-[.14em] text-emerald-800"><Zap className="size-3.5" /> The Founding Fifty</div><h2 className="section-title">50 local businesses.<br />25 industries. One mission.</h2><p className="section-copy">The first fifty local businesses can earn a founding number and Founder badge while their annual membership remains active or in an approved grace period, plus a place in the cohort shaping Optimize Local Connect.</p><ArrowLink href="/founders">Explore the Founding Partner offer</ArrowLink></div><div className="scroll-reveal grid gap-4 sm:grid-cols-2">{[[Store,"Two seats per industry","Clear category exclusivity with live, honest availability."],[BadgeCheck,"Founder recognition","A founding number and badge attached to an eligible organization."],[Banknote,founderPrice,"Charged today and automatically renewed every 12 months until canceled."],[Users,"Help shape Connect","Feature voting, founder roundtables, and spotlight eligibility."]].map(([Icon,title,copy]) => {const C=Icon as typeof Store; return <article key={title as string} className="rounded-2xl bg-white/80 p-6 shadow-sm backdrop-blur"><C className="size-5 text-emerald-700" /><h3 className="mt-7 text-lg font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy as string}</p></article>})}</div></div></section>

    <section id="managers" className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="mx-auto max-w-3xl text-center scroll-reveal"><p className="section-kicker">Property Management launch</p><h2 className="section-title">More control. Less operational drag.</h2><p className="section-copy mx-auto">Connect turns fragmented local service work into a repeatable operating advantage.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 md:grid-cols-2">{managerBenefits.map(({title,copy,icon:Icon}) => <article key={title} className="bg-white p-7 sm:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-slate-950"><Icon className="size-5 text-emerald-400" /></span><h3 className="mt-12 text-2xl font-bold tracking-tight">{title}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

    <section id="impact" className="bg-slate-950 py-24 text-white sm:py-32"><div className="scroll-reveal mx-auto max-w-5xl px-5 text-center sm:px-8"><p className="section-kicker text-emerald-400">Community impact & founder manifesto</p><blockquote className="mt-7 text-4xl font-semibold leading-tight tracking-[-.045em] sm:text-6xl">“{PLATFORM_BRAND.manifesto}”</blockquote><p className="mt-8 text-sm font-bold uppercase tracking-[.18em] text-slate-400">{PLATFORM_BRAND.parentName}</p></div></section>

    <section id="pricing" className="scroll-reveal bg-[#f1f3ee] py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="max-w-3xl"><p className="section-kicker">Property Management launch plans</p><h2 className="section-title">Start lean. Scale without switching systems.</h2><p className="section-copy">Founding access for our first vertical is intentionally simple. We’ll confirm final plan details before billing begins.</p></div><div className="mt-14 grid items-stretch gap-5 lg:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`relative flex flex-col rounded-[1.75rem] p-7 sm:p-8 ${plan.featured?'bg-slate-950 text-white shadow-2xl shadow-slate-950/20 lg:-translate-y-4':'border border-slate-200 bg-white'}`}>{plan.featured?<span className="absolute right-6 top-6 rounded-full bg-emerald-400 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-emerald-950">Most popular</span>:null}<p className={`text-sm font-bold ${plan.featured?'text-emerald-400':'text-emerald-700'}`}>{plan.name}</p><p className="mt-6 text-4xl font-semibold tracking-tight">{plan.price}</p><p className={`mt-2 text-xs ${plan.featured?'text-slate-400':'text-slate-500'}`}>{plan.suffix}</p><p className={`mt-6 text-sm leading-6 ${plan.featured?'text-slate-300':'text-slate-600'}`}>{plan.copy}</p><ul className={`mt-8 space-y-3 border-t pt-7 ${plan.featured?'border-white/10':'border-slate-200'}`}>{plan.features.map(feature => <li key={feature} className="flex gap-2.5 text-sm"><Check className={`mt-0.5 size-4 shrink-0 ${plan.featured?'text-emerald-400':'text-emerald-600'}`} />{feature}</li>)}</ul><a href="#contact" className={`mt-9 inline-flex min-h-12 items-center justify-center rounded-full px-5 text-sm font-bold transition ${plan.featured?'bg-emerald-400 text-emerald-950 hover:bg-emerald-300':'bg-slate-950 text-white hover:bg-emerald-700'}`}>{plan.action}</a></article>)}</div></div></section>

    <section id="faq" className="bg-white py-24 sm:py-32"><div className="mx-auto grid max-w-[90rem] gap-14 px-5 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-12"><div className="scroll-reveal"><p className="section-kicker">FAQ</p><h2 className="section-title">Good questions.<br />Clear answers.</h2><p className="section-copy text-base">Still curious? Send us a note and we’ll respond directly.</p><a href="mailto:hello@optimizelocal.com" className="mt-7 inline-flex items-center text-sm font-bold text-emerald-700 hover:text-emerald-800">hello@optimizelocal.com <ArrowRight className="ml-2 size-4" /></a></div><div className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(([question,answer]) => <details key={question} className="group py-1"><summary className="flex min-h-18 cursor-pointer list-none items-center justify-between gap-5 py-5 text-left font-bold text-slate-900"><span>{question}</span><span className="grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-lg font-light transition group-open:rotate-45">+</span></summary><p className="max-w-3xl pb-6 pr-12 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section id="contact" className="bg-white px-5 pb-5 sm:px-8 sm:pb-8 lg:px-12 lg:pb-12"><div className="scroll-reveal relative mx-auto max-w-[90rem] overflow-hidden rounded-[2rem] bg-emerald-700 px-6 py-16 text-white sm:px-12 sm:py-20 lg:px-20"><div aria-hidden="true" className="absolute -right-24 -top-24 size-80 rounded-full border-[50px] border-white/5" /><div className="relative z-10 grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-200">Connect locally. Grow together.</p><h2 className="mt-5 max-w-4xl text-4xl font-semibold leading-[.96] tracking-[-.05em] sm:text-6xl lg:text-7xl">Spend less time chasing.<br />More time moving forward.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-emerald-100">Join the founding group of property managers and local providers shaping the first Optimize Local Connect industry vertical.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><ArrowLink href="mailto:hello@optimizelocal.com?subject=Optimize%20Local%20Connect%20Early%20Access" light>Request early access</ArrowLink><a href="mailto:hello@optimizelocal.com?subject=Founding%20Local%20Provider%20Program" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/25 px-6 text-sm font-bold text-white transition hover:bg-white/10">Apply as a provider</a></div></div></div></section>

    <footer className="bg-white"><div className="mx-auto grid max-w-[90rem] gap-10 px-5 py-10 sm:px-8 md:grid-cols-[1fr_auto] md:items-end lg:px-12"><div><Logo /><p className="mt-5 max-w-sm text-sm leading-6 text-slate-500">{PLATFORM_BRAND.description}</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500"><a href="#how-it-works" className="hover:text-slate-900">Platform</a><Link href="/company" className="hover:text-slate-900">Company</Link><a href="#pricing" className="hover:text-slate-900">Pricing</a><a href="#faq" className="hover:text-slate-900">FAQ</a><Link href="/sign-in" className="hover:text-slate-900">Sign in</Link></div></div><div className="mx-auto flex max-w-[90rem] flex-col gap-3 border-t border-slate-200 px-5 py-6 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-12"><p>© 2026 {PLATFORM_BRAND.parentName}. {PLATFORM_BRAND.productName} is a platform of Optimize Local™.</p><p>{PLATFORM_BRAND.mission}</p></div></footer>
  </main>;
}
