import Link from "next/link";
import {
  ArrowRight,
  BadgeCheck,
  Banknote,
  BellRing,
  Building2,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleDollarSign,
  Clock3,
  Home as HomeIcon,
  KeyRound,
  MapPin,
  MessageSquareText,
  PackageCheck,
  ShieldCheck,
  Sparkles,
  SprayCan,
  Star,
  Store,
  TimerReset,
  Users,
  WashingMachine,
  Wrench,
  Zap,
} from "lucide-react";
import { Logo } from "@/src/components/brand/logo";
import { PLATFORM_BRAND } from "@/src/domain/platform/brand";

const steps = [
  { number: "01", title: "Tell us what needs attention", copy: "Create a request in under a minute with the property, priority, photos, and access details.", icon: MessageSquareText },
  { number: "02", title: "Get the right local match", copy: "Connect with verified local providers who serve your city, specialize in the work, and are ready to respond.", icon: MapPin },
  { number: "03", title: "Approve, track, and close", copy: "Compare quotes, follow progress, receive invoices, and keep the complete record in one calm workspace.", icon: CheckCircle2 },
];

const services = [
  { id: "cleaning", eyebrow: "Turn-ready cleaning", title: "Every clean, scoped and accountable.", copy: "Schedule recurring, move-out, deep, and common-area cleaning with room-level details and photo proof of completion.", icon: SprayCan, tint: "bg-[#e9f8f1]", ink: "text-emerald-700", details: ["Recurring schedules", "Turn checklists", "Photo documentation"] },
  { id: "appliances", eyebrow: "Appliance services", title: "Know what is installed. Fix it faster.", copy: "Keep model, serial, warranty, and service history connected to every unit—then route repair or replacement to the right technician.", icon: WashingMachine, tint: "bg-[#eef2ff]", ink: "text-indigo-700", details: ["Asset inventory", "Warranty tracking", "Repair history"] },
  { id: "emergency", eyebrow: "Emergency repairs", title: "Urgent work without the scramble.", copy: "Escalate leaks, no-cooling calls, electrical hazards, and lockouts to on-call providers with clear safety status and response tracking.", icon: BellRing, tint: "bg-[#fff1ed]", ink: "text-orange-700", details: ["Priority escalation", "On-call matching", "Live status updates"] },
];

const managerBenefits = [
  { title: "Hours back every week", copy: "Replace calls, texts, spreadsheets, and repeated follow-ups with one shared operating record.", icon: Clock3 },
  { title: "Spend with confidence", copy: "Compare quotes, preserve rate history, and understand cost by property, provider, service, and city.", icon: CircleDollarSign },
  { title: "A stronger provider network", copy: "See credentials, service coverage, responsiveness, ratings, and outcomes before awarding work.", icon: ShieldCheck },
  { title: "Ready for every market", copy: "Standardize the playbook once, then expand into new cities without rebuilding operations.", icon: Building2 },
];

const plans = [
  { name: "Starter", price: "$0", suffix: "during early access", copy: "For independent managers building a better local provider workflow.", features: ["Up to 25 units", "Local provider marketplace", "Service requests and quotes", "Email support"], featured: false, action: "Join early access" },
  { name: "Portfolio", price: "$149", suffix: "per month", copy: "For growing property teams managing multiple buildings and providers.", features: ["Up to 500 units", "Team roles and approvals", "Provider performance history", "Work orders and invoices", "Priority support"], featured: true, action: "Start with Portfolio" },
  { name: "Enterprise", price: "Let’s talk", suffix: "built around your operation", copy: "For multi-market operators that need governance, integration, and scale.", features: ["Unlimited markets", "Advanced permissions", "Custom integrations", "Data migration support", "Dedicated success lead"], featured: false, action: "Talk to our team" },
];

const faqs = [
  ["Is Optimize Local Connect only for property management?", "No. Property Management is the first industry served. The shared platform is designed so future industries can add their own workflows without rebuilding identity, organizations, local discovery, communication, analytics, or AI foundations."],
  ["Is this just a provider directory?", "No. Optimize Local Connect is a community platform and transactional marketplace: requests, matching, quotes, work orders, invoices, communication, performance, and records stay connected."],
  ["How are local providers verified?", "Verification is designed to include identity, business registration, licensing, insurance, service coverage, and ongoing performance signals. Requirements can vary by service, industry, and market."],
  ["Can our existing providers join?", "Yes. Invite trusted partners into your private network while also discovering qualified local providers when you need more coverage or a new specialty."],
  ["Does it work across multiple cities?", "Yes. Cities, markets, organizations, properties, provider coverage, and access are modeled independently so teams can expand without duplicating systems."],
  ["Can technicians use it from the field?", "Yes. The experience is mobile-first, with role-specific access so technicians can see assignments, update status, and add job documentation without navigating administrative screens."],
  ["When will pricing begin?", "Founding teams receive early-access terms before paid plans begin. Final pricing may evolve with the product, and founding participants will receive advance notice."],
];

function ArrowLink({ href, children, light = false }: { href: string; children: React.ReactNode; light?: boolean }) {
  return <a href={href} className={`group inline-flex min-h-12 items-center justify-center rounded-full px-6 text-sm font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2 ${light ? "bg-white text-slate-950 hover:bg-emerald-50" : "bg-slate-950 text-white shadow-lg shadow-slate-950/10 hover:-translate-y-0.5 hover:bg-emerald-700"}`}>{children}<ArrowRight aria-hidden="true" className="ml-2 size-4 transition-transform group-hover:translate-x-1" /></a>;
}

export default function Home() {
  return <main className="min-h-dvh overflow-hidden bg-[#f7f8f4] text-slate-950">
    <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-[#f7f8f4]/85 backdrop-blur-xl">
      <div className="mx-auto flex h-18 max-w-[90rem] items-center justify-between px-5 sm:px-8 lg:px-12"><Logo />
        <nav aria-label="Primary navigation" className="hidden items-center gap-7 lg:flex">
          {[['Platform','#how-it-works'],['Local marketplace','#marketplace'],['Property Management','#services'],['For providers','#providers'],['Pricing','#pricing'],['FAQ','#faq']].map(([label, href]) => <a key={href} href={href} className="text-sm font-medium text-slate-600 transition hover:text-slate-950">{label}</a>)}
        </nav>
        <div className="flex items-center gap-2"><Link href="/sign-in" className="hidden min-h-11 items-center rounded-full px-4 text-sm font-semibold text-slate-700 hover:bg-white sm:inline-flex">Sign in</Link><a href="#contact" className="inline-flex min-h-11 items-center rounded-full bg-slate-950 px-5 text-sm font-semibold text-white transition hover:bg-emerald-700">Get early access</a></div>
      </div>
    </header>

    <section className="relative isolate">
      <div aria-hidden="true" className="hero-orb hero-orb-one" /><div aria-hidden="true" className="hero-orb hero-orb-two" />
      <div className="mx-auto grid min-h-[calc(100dvh-4.5rem)] max-w-[90rem] items-center gap-16 px-5 py-16 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:px-12 lg:py-24">
        <div className="relative z-10 max-w-3xl animate-rise">
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-emerald-200/80 bg-white/75 px-3.5 py-2 text-xs font-bold uppercase tracking-[.14em] text-emerald-800 shadow-sm backdrop-blur"><Sparkles className="size-3.5" /> {PLATFORM_BRAND.companyTagline}</div>
          <h1 className="text-[clamp(3.5rem,7.6vw,7.6rem)] font-semibold leading-[.86] tracking-[-.072em] text-slate-950">Save Time.<br />Save Money.<br /><span className="text-emerald-700">Strengthen<br className="hidden sm:block" /> Communities.</span></h1>
          <p className="mt-8 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">{PLATFORM_BRAND.productName} is the AI-ready community platform connecting local organizations with trusted providers, shared workflows, and better decisions.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><ArrowLink href="#contact">Get early access</ArrowLink><a href="#how-it-works" className="inline-flex min-h-12 items-center justify-center rounded-full border border-slate-200 bg-white/80 px-6 text-sm font-bold text-slate-800 transition hover:border-slate-300 hover:bg-white">See how it works</a></div>
          <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-600" /> No credit card</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-600" /> Founding access</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-600" /> Multi-city ready</span></div>
        </div>

        <div className="relative mx-auto w-full max-w-2xl animate-rise-delayed lg:mr-0">
          <div className="hero-dashboard relative rounded-[2rem] border border-white/80 bg-white/88 p-3 shadow-[0_40px_120px_rgba(15,23,42,.18)] backdrop-blur-xl sm:p-5">
            <div className="flex items-center justify-between px-2 pb-5 pt-2"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Operations today</p><p className="mt-1 text-lg font-bold">Northside portfolio</p></div><div className="flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><span className="size-1.5 rounded-full bg-emerald-500 shadow-[0_0_0_4px_rgba(16,185,129,.12)]" /> Live</div></div>
            <div className="grid grid-cols-3 gap-2 sm:gap-3">{[['48','Properties'],['9','Open jobs'],['96%','On time']].map(([value,label]) => <div key={label} className="rounded-2xl bg-slate-50 p-3 sm:p-4"><p className="text-xl font-bold tracking-tight sm:text-2xl">{value}</p><p className="mt-1 text-[10px] text-slate-500 sm:text-xs">{label}</p></div>)}</div>
            <div className="mt-3 rounded-2xl border border-slate-100 bg-white p-4 shadow-[0_8px_30px_rgba(15,23,42,.06)] sm:p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-orange-50"><Wrench className="size-5 text-orange-700" /></span><div className="min-w-0"><p className="truncate text-sm font-bold">No cooling · Unit 204</p><p className="mt-0.5 truncate text-xs text-slate-500">Riverview Flats · HVAC</p></div></div><span className="rounded-full bg-rose-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-rose-700">Urgent</span></div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><div className="flex -space-x-2">{["AR","HC","MT"].map((initials, index) => <span key={initials} className={`grid size-8 place-items-center rounded-full border-2 border-white text-[9px] font-black ${['bg-emerald-100 text-emerald-800','bg-sky-100 text-sky-800','bg-amber-100 text-amber-800'][index]}`}>{initials}</span>)}</div><span className="flex items-center gap-1.5 text-xs font-semibold text-slate-700"><BadgeCheck className="size-4 text-emerald-600" /> 3 verified matches</span></div></div>
            <div className="mt-3 grid gap-3 sm:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center justify-between"><p className="text-xs text-slate-400">This month</p><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">↓ 18% cost</span></div><p className="mt-4 text-2xl font-bold">$12,840</p><div className="mt-4 flex h-10 items-end gap-1">{[42,58,38,72,52,86,63,92,71,100,82,68].map((height,index) => <span key={index} className="flex-1 rounded-sm bg-emerald-400/70" style={{height:`${height}%`}} />)}</div></div><div className="rounded-2xl border border-slate-100 p-4"><p className="text-xs text-slate-500">Average response</p><p className="mt-2 text-2xl font-bold">18 min</p><p className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><TimerReset className="size-4" /> 7 min faster</p></div></div>
          </div>
          <div className="float-card absolute -bottom-7 -left-5 hidden items-center gap-3 rounded-2xl border border-white bg-white p-3.5 shadow-xl sm:flex"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50"><PackageCheck className="size-5 text-emerald-700" /></span><div><p className="text-xs text-slate-500">Work order completed</p><p className="text-sm font-bold">Turn clean · Unit 8B</p></div></div>
        </div>
      </div>
    </section>

    <section className="border-y border-slate-200 bg-white py-7"><div className="mx-auto flex max-w-[90rem] flex-wrap items-center justify-center gap-x-10 gap-y-4 px-5 text-xs font-bold uppercase tracking-[.16em] text-slate-400 sm:px-8 lg:justify-between lg:px-12"><span>Launching first for Property Management</span>{[[HomeIcon,"Multifamily"],[Building2,"Commercial"],[KeyRound,"Single-family"],[Store,"Local providers"]].map(([Icon,label]) => { const C=Icon as typeof HomeIcon; return <span key={label as string} className="flex items-center gap-2 text-slate-500"><C className="size-4" />{label as string}</span>})}</div></section>

    <section id="how-it-works" className="scroll-reveal bg-white py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="max-w-3xl"><p className="section-kicker">One community platform</p><h2 className="section-title">Shared foundations.<br />Industry-specific workflows.</h2><p className="section-copy">Identity, organizations, local discovery, transactions, communication, analytics, and AI readiness form one reusable platform. Property Management is the first vertical built on it.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{steps.map(({number,title,copy,icon:Icon}) => <article key={number} className="group rounded-[1.75rem] border border-slate-200 bg-[#fafbf8] p-6 transition duration-500 hover:-translate-y-1 hover:border-emerald-200 hover:shadow-xl hover:shadow-emerald-950/5 sm:p-8"><div className="flex items-center justify-between"><span className="text-sm font-black text-emerald-700">{number}</span><span className="grid size-11 place-items-center rounded-2xl bg-white shadow-sm"><Icon className="size-5 text-slate-700" /></span></div><h3 className="mt-20 text-2xl font-bold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

    <section id="marketplace" className="scroll-reveal bg-slate-950 py-24 text-white sm:py-32"><div className="mx-auto grid max-w-[90rem] gap-14 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-12"><div><p className="section-kicker text-emerald-400">Local provider marketplace</p><h2 className="section-title text-white">Local expertise.<br />Verified confidence.</h2><p className="section-copy text-slate-400">Find providers by service, city, availability, credentials, and real performance—not whoever happens to answer the phone first.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Verified credentials","City-level coverage","Response history","Transparent quotes"].map(item => <span key={item} className="flex items-center gap-2 text-sm text-slate-300"><Check className="size-4 text-emerald-400" />{item}</span>)}</div><a href="#providers" className="mt-9 inline-flex items-center text-sm font-bold text-emerald-400 hover:text-emerald-300">Explore the founding provider program <ChevronRight className="ml-1 size-4" /></a></div>
      <div className="rounded-[2rem] bg-slate-900 p-4 ring-1 ring-white/10 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Recommended nearby</p><h3 className="mt-1 text-xl font-bold">HVAC · Dallas market</h3></div><span className="rounded-full bg-white/5 px-3 py-1.5 text-xs text-slate-400">12 providers</span></div><div className="mt-6 space-y-3">{[["AirRight Mechanical","4.9","14 min","Verified + insured","AR"],["Metro Climate Co.","4.8","22 min","Commercial specialist","MC"],["North Texas Comfort","4.7","31 min","24/7 emergency","NT"]].map(([name,rating,response,badge,initials],index) => <article key={name} className={`flex items-center gap-3 rounded-2xl border p-3.5 sm:p-4 ${index===0?'border-emerald-400/30 bg-emerald-400/5':'border-white/5 bg-white/[.025]'}`}><span className={`grid size-11 shrink-0 place-items-center rounded-xl text-xs font-black ${index===0?'bg-emerald-400 text-emerald-950':'bg-white/10 text-slate-300'}`}>{initials}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-bold">{name}</p>{index===0?<BadgeCheck className="size-4 shrink-0 text-emerald-400" />:null}</div><p className="mt-1 truncate text-xs text-slate-500">{badge}</p></div><div className="text-right"><p className="flex items-center justify-end gap-1 text-sm font-bold"><Star className="size-3.5 fill-amber-400 text-amber-400" />{rating}</p><p className="mt-1 text-[10px] text-slate-500">{response} response</p></div></article>)}</div></div>
    </div></section>

    <section id="services" className="bg-[#f7f8f4] py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="max-w-3xl scroll-reveal"><p className="section-kicker">First vertical · Property Management</p><h2 className="section-title">The everyday services that keep communities moving.</h2><p className="section-copy">Purpose-built property workflows run on the same Connect platform that will support future industries.</p></div><div className="mt-14 space-y-5">{services.map(({id,eyebrow,title,copy,icon:Icon,tint,ink,details},index) => <article id={id} key={id} className="scroll-reveal grid overflow-hidden rounded-[2rem] border border-slate-200 bg-white lg:grid-cols-2"><div className={`flex min-h-80 flex-col justify-between p-7 sm:p-10 lg:p-12 ${index%2===1?'lg:order-2':''}`}><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">{eyebrow}</p><h3 className="mt-4 max-w-xl text-3xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">{title}</h3><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">{copy}</p></div><div className="mt-10 flex flex-wrap gap-2">{details.map(detail => <span key={detail} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">{detail}</span>)}</div></div><div className={`grid min-h-80 place-items-center p-8 sm:p-12 ${tint} ${index%2===1?'lg:order-1':''}`}><div className="relative grid size-48 place-items-center rounded-[3rem] bg-white shadow-[0_30px_70px_rgba(15,23,42,.12)] sm:size-60"><div aria-hidden="true" className={`absolute inset-5 rounded-[2.25rem] border border-current opacity-10 ${ink}`} /><Icon className={`size-20 sm:size-24 ${ink}`} strokeWidth={1.25} /><span className="absolute -right-3 -top-3 grid size-14 place-items-center rounded-2xl bg-slate-950 text-white shadow-xl"><Check className="size-6" /></span></div></div></article>)}</div></div></section>

    <section id="testimonials" className="scroll-reveal bg-white py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="section-kicker">Built with operators</p><h2 className="section-title">The standard property teams have been waiting for.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Founding cohort stories will appear here as teams complete their first Property Management workflows.</p></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[["Fewer follow-ups. Faster turns.","Property manager","Multifamily portfolio"],["Better work. Clearer expectations.","Founding provider","Local service company"],["One place to see what’s happening.","Operations leader","Multi-market team"]].map(([quote,role,context]) => <figure key={quote} className="rounded-[1.75rem] border border-slate-200 bg-[#fafbf8] p-7 sm:p-8"><div className="flex gap-1 text-amber-400">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-4 fill-current" />)}</div><blockquote className="mt-8 text-2xl font-semibold leading-tight tracking-tight text-slate-900">“{quote}”</blockquote><figcaption className="mt-10 border-t border-slate-200 pt-5"><p className="text-sm font-bold text-slate-800">{role}</p><p className="mt-1 text-xs text-slate-500">{context} · testimonial placeholder</p></figcaption></figure>)}</div></div></section>

    <section id="providers" className="bg-[#dff4e8] py-24 sm:py-32"><div className="mx-auto grid max-w-[90rem] gap-12 px-5 sm:px-8 lg:grid-cols-[1fr_.9fr] lg:items-center lg:px-12"><div className="scroll-reveal"><div className="inline-flex items-center gap-2 rounded-full bg-white/70 px-3.5 py-2 text-xs font-black uppercase tracking-[.14em] text-emerald-800"><Zap className="size-3.5" /> Founding Local Provider Program</div><h2 className="section-title">Grow with organizations in your community.</h2><p className="section-copy">Founding providers help shape the marketplace, build an early performance record, and receive preferred launch benefits as new local markets and industries open.</p><ArrowLink href="#contact">Apply as a founding provider</ArrowLink></div><div className="scroll-reveal grid gap-4 sm:grid-cols-2">{[[Store,"Qualified local demand","Match with local organizations seeking your actual services."],[BadgeCheck,"Stand out on trust","Show verification, specialties, availability, and performance."],[Banknote,"Quote the right work","Review clear scope before spending time on an estimate."],[Users,"Build lasting accounts","Turn one successful job into a trusted operating relationship."]].map(([Icon,title,copy]) => {const C=Icon as typeof Store; return <article key={title as string} className="rounded-2xl bg-white/80 p-6 shadow-sm backdrop-blur"><C className="size-5 text-emerald-700" /><h3 className="mt-7 text-lg font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy as string}</p></article>})}</div></div></section>

    <section id="managers" className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="mx-auto max-w-3xl text-center scroll-reveal"><p className="section-kicker">Property Management launch</p><h2 className="section-title">More control. Less operational drag.</h2><p className="section-copy mx-auto">Connect turns fragmented local service work into a repeatable operating advantage.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 md:grid-cols-2">{managerBenefits.map(({title,copy,icon:Icon}) => <article key={title} className="bg-white p-7 sm:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-slate-950"><Icon className="size-5 text-emerald-400" /></span><h3 className="mt-12 text-2xl font-bold tracking-tight">{title}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

    <section className="bg-slate-950 py-24 text-white sm:py-32"><div className="scroll-reveal mx-auto max-w-5xl px-5 text-center sm:px-8"><p className="section-kicker text-emerald-400">Founder manifesto</p><blockquote className="mt-7 text-4xl font-semibold leading-tight tracking-[-.045em] sm:text-6xl">“{PLATFORM_BRAND.manifesto}”</blockquote><p className="mt-8 text-sm font-bold uppercase tracking-[.18em] text-slate-400">{PLATFORM_BRAND.parentName}</p></div></section>

    <section id="pricing" className="scroll-reveal bg-[#f1f3ee] py-24 sm:py-32"><div className="mx-auto max-w-[90rem] px-5 sm:px-8 lg:px-12"><div className="max-w-3xl"><p className="section-kicker">Property Management launch plans</p><h2 className="section-title">Start lean. Scale without switching systems.</h2><p className="section-copy">Founding access for our first vertical is intentionally simple. We’ll confirm final plan details before billing begins.</p></div><div className="mt-14 grid items-stretch gap-5 lg:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`relative flex flex-col rounded-[1.75rem] p-7 sm:p-8 ${plan.featured?'bg-slate-950 text-white shadow-2xl shadow-slate-950/20 lg:-translate-y-4':'border border-slate-200 bg-white'}`}>{plan.featured?<span className="absolute right-6 top-6 rounded-full bg-emerald-400 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-emerald-950">Most popular</span>:null}<p className={`text-sm font-bold ${plan.featured?'text-emerald-400':'text-emerald-700'}`}>{plan.name}</p><p className="mt-6 text-4xl font-semibold tracking-tight">{plan.price}</p><p className={`mt-2 text-xs ${plan.featured?'text-slate-400':'text-slate-500'}`}>{plan.suffix}</p><p className={`mt-6 text-sm leading-6 ${plan.featured?'text-slate-300':'text-slate-600'}`}>{plan.copy}</p><ul className={`mt-8 space-y-3 border-t pt-7 ${plan.featured?'border-white/10':'border-slate-200'}`}>{plan.features.map(feature => <li key={feature} className="flex gap-2.5 text-sm"><Check className={`mt-0.5 size-4 shrink-0 ${plan.featured?'text-emerald-400':'text-emerald-600'}`} />{feature}</li>)}</ul><a href="#contact" className={`mt-9 inline-flex min-h-12 items-center justify-center rounded-full px-5 text-sm font-bold transition ${plan.featured?'bg-emerald-400 text-emerald-950 hover:bg-emerald-300':'bg-slate-950 text-white hover:bg-emerald-700'}`}>{plan.action}</a></article>)}</div></div></section>

    <section id="faq" className="bg-white py-24 sm:py-32"><div className="mx-auto grid max-w-[90rem] gap-14 px-5 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-12"><div className="scroll-reveal"><p className="section-kicker">FAQ</p><h2 className="section-title">Good questions.<br />Clear answers.</h2><p className="section-copy text-base">Still curious? Send us a note and we’ll respond directly.</p><a href="mailto:hello@optimizelocal.com" className="mt-7 inline-flex items-center text-sm font-bold text-emerald-700 hover:text-emerald-800">hello@optimizelocal.com <ArrowRight className="ml-2 size-4" /></a></div><div className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(([question,answer]) => <details key={question} className="group py-1"><summary className="flex min-h-18 cursor-pointer list-none items-center justify-between gap-5 py-5 text-left font-bold text-slate-900"><span>{question}</span><span className="grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-lg font-light transition group-open:rotate-45">+</span></summary><p className="max-w-3xl pb-6 pr-12 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section id="contact" className="bg-white px-5 pb-5 sm:px-8 sm:pb-8 lg:px-12 lg:pb-12"><div className="scroll-reveal relative mx-auto max-w-[90rem] overflow-hidden rounded-[2rem] bg-emerald-700 px-6 py-16 text-white sm:px-12 sm:py-20 lg:px-20"><div aria-hidden="true" className="absolute -right-24 -top-24 size-80 rounded-full border-[50px] border-white/5" /><div className="relative z-10 grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-200">Connect locally. Grow together.</p><h2 className="mt-5 max-w-4xl text-4xl font-semibold leading-[.96] tracking-[-.05em] sm:text-6xl lg:text-7xl">Spend less time chasing.<br />More time moving forward.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-emerald-100">Join the founding group of property managers and local providers shaping the first Optimize Local Connect industry vertical.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><ArrowLink href="mailto:hello@optimizelocal.com?subject=Optimize%20Local%20Connect%20Early%20Access" light>Request early access</ArrowLink><a href="mailto:hello@optimizelocal.com?subject=Founding%20Local%20Provider%20Program" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/25 px-6 text-sm font-bold text-white transition hover:bg-white/10">Apply as a provider</a></div></div></div></section>

    <footer className="bg-white"><div className="mx-auto grid max-w-[90rem] gap-10 px-5 py-10 sm:px-8 md:grid-cols-[1fr_auto] md:items-end lg:px-12"><div><Logo /><p className="mt-5 max-w-sm text-sm leading-6 text-slate-500">{PLATFORM_BRAND.description}</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500"><a href="#how-it-works" className="hover:text-slate-900">Platform</a><a href="#pricing" className="hover:text-slate-900">Pricing</a><a href="#faq" className="hover:text-slate-900">FAQ</a><Link href="/sign-in" className="hover:text-slate-900">Sign in</Link></div></div><div className="mx-auto flex max-w-[90rem] flex-col gap-3 border-t border-slate-200 px-5 py-6 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-12"><p>© 2026 {PLATFORM_BRAND.parentName}. {PLATFORM_BRAND.productName} is a platform of Optimize Local™.</p><p>{PLATFORM_BRAND.companyTagline}</p></div></footer>
  </main>;
}
