import { redirect } from "next/navigation";
import { manageFirebaseVendorNetwork } from "./actions";
import { requireUser } from "@/src/lib/auth/session";
import { isFirebaseOperationalBackend } from "@/src/lib/firebase/platform";
import { listFirebaseVendorNetwork } from "@/src/lib/firebase/vendor-profiles";

export const dynamic="force-dynamic";
export default async function VendorNetworkPage(){
  const user=await requireUser();if(!user.isSuperAdmin)redirect("/dashboard");if(!isFirebaseOperationalBackend())return <section className="rounded-2xl border bg-white p-8"><h1 className="text-3xl font-semibold">Firebase Vendor Network</h1><p className="mt-3 text-sm text-slate-500">Available when the bounded Firebase operational backend flag is enabled.</p></section>;
  const vendors=await listFirebaseVendorNetwork();
  return <div><p className="text-sm font-semibold text-emerald-700">Firebase operations</p><h1 className="mt-1 text-4xl font-semibold">Vendor Network</h1><p className="mt-3 text-sm text-slate-500">Profile review, organization status, publication, and opportunity eligibility. Financial changes remain in Stripe billing controls.</p><div className="mt-7 grid gap-4">{vendors.map(vendor=><article key={vendor.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-4 lg:grid-cols-[1fr_1fr_auto]"><div><h2 className="font-bold">{String(vendor.name)}</h2><p className="mt-2 text-xs text-slate-500">Organization: {String(vendor.status)} · Profile {vendor.profileCompleteness.completed}/{vendor.profileCompleteness.total}</p><p className={`mt-2 text-xs font-black ${vendor.opportunityEligible?"text-emerald-700":"text-amber-700"}`}>Opportunity eligible: {vendor.opportunityEligible?"Yes":"No"}</p></div><div className="text-xs text-slate-600"><p>Membership: {String(vendor.membership?.tier??"none")} · {String(vendor.membership?.status??"inactive")}</p><p className="mt-1">Membership ID: {vendor.membership?.id??"—"}</p><p className="mt-1">Founder category: {String(vendor.membership?.categorySlug??"—")}</p><p className="mt-1">Areas: {vendor.profile?.serviceAreaKeys.join(", ")||"Not provided"}</p><p className="mt-1">Approval: {vendor.profile?.approvalState??"No profile"} · Publication: {vendor.profile?.publicationState??"unpublished"}</p></div>{vendor.profile?<form action={manageFirebaseVendorNetwork} className="flex flex-wrap gap-2 lg:max-w-sm"><input type="hidden" name="organizationId" value={vendor.id}/><select name="action" className="min-h-10 rounded-xl border px-3 text-sm"><option value="approve">Approve</option><option value="request_changes">Request changes</option><option value="publish">Publish</option><option value="unpublish">Unpublish</option><option value="suspend">Suspend</option><option value="reactivate">Reactivate</option></select><input name="note" className="min-h-10 rounded-xl border px-3 text-sm" placeholder="Review note"/><button className="rounded-xl bg-slate-950 px-4 text-xs font-bold text-white">Apply</button></form>:null}</div>{vendor.profile?<details className="mt-4 rounded-xl bg-slate-50 p-4 text-xs text-slate-600"><summary className="cursor-pointer font-bold text-slate-900">Inspect profile and membership</summary><p className="mt-3 leading-5">{vendor.profile.description||"No description"}</p><p className="mt-2">Services: {vendor.profile.services.join(", ")||"Not provided"}</p><p className="mt-1">Public contact: {vendor.profile.publicEmail??"—"} · {vendor.profile.publicPhone??"—"}</p><p className="mt-1">Consent: {vendor.profile.publicDisplayConsent?"Yes":"No"} · Priority: {vendor.membership?.priority??"—"}</p></details>:null}</article>)}</div></div>;
}
