export const FOUNDING_VENDOR_SPOT_CAPACITY = 50;

export const FOUNDING_VENDOR_RESERVED_CATEGORIES = [
  "HVAC",
  "Electrician",
  "Appliance Repair",
] as const;

export const FOUNDING_VENDOR_SPOTS_RESERVED = FOUNDING_VENDOR_RESERVED_CATEGORIES.length;
export const FOUNDING_VENDOR_RESERVATION_SUMMARY = `${FOUNDING_VENDOR_SPOTS_RESERVED} of ${FOUNDING_VENDOR_SPOT_CAPACITY} Founder Spots Reserved`;
